// ─── Static fallback products for categories not covered by Shopify ───
// Shared module so both the products API route and individual product lookups
// can reference the same curated data.

export interface StaticProduct {
  id: string
  name: string
  slug: string
  description: string
  price: number
  compareAtPrice: number | null
  images: string[]
  category: string
  categorySlug: string
  stock: number
  rating: number
  reviewCount: number
  featured: boolean
  tags: string[]
  platform: string | null
  isExternal: boolean
  sourceUrl: string | null
  affiliateUrl: string | null
  deliveryEstimate: string | null
}

const STATIC_OFFICE_PRODUCTS: StaticProduct[] = [
  {
    id: 'static-corp-gift-1',
    name: 'Executive Gift Hamper',
    slug: 'executive-gift-hamper',
    description:
      'A premium corporate gift hamper featuring artisan chocolates, a leather-bound planner, premium tea collection, and a personalized thank-you card. Elegantly packaged in a matte black box with gold foil branding.',
    price: 1800,
    compareAtPrice: 2200,
    images: ['/images/products/corp-gift-1.jpg', '/images/products/corp-gift-1-2.jpg', '/images/products/corp-gift-1-3.jpg'],
    category: 'Corporate Gifts',
    categorySlug: 'office-corporate-gifts',
    stock: 25,
    rating: 4.8,
    reviewCount: 56,
    featured: true,
    tags: ['hamper', 'corporate', 'executive', 'gifting', 'new-arrival'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-corp-gift-2',
    name: 'Premium Pen & Watch Gift Set',
    slug: 'premium-pen-watch-gift-set',
    description:
      'An exclusive gift set pairing a Swiss automatic watch with a handcrafted fountain pen in a shared walnut presentation box. The watch features a minimalist silver dial and Italian leather strap. Engravable.',
    price: 4800,
    compareAtPrice: null,
    images: ['/images/products/corp-gift-2.jpg', '/images/products/corp-gift-2-2.jpg', '/images/products/corp-gift-2-3.jpg'],
    category: 'Corporate Gifts',
    categorySlug: 'office-corporate-gifts',
    stock: 8,
    rating: 4.9,
    reviewCount: 18,
    featured: true,
    tags: ['watch', 'pen', 'gift-set', 'corporate', 'engravable', 'new-arrival'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-corp-gift-3',
    name: 'Luxury Corporate Gift Box',
    slug: 'luxury-corporate-gift-box',
    description:
      'An exquisite corporate gift box featuring a curated selection of premium items including artisan chocolates, a silk scarf, a crystal paperweight, and a handwritten note. Wrapped in signature gold ribbon.',
    price: 2400,
    compareAtPrice: 2800,
    images: ['/images/products/corp-gift-3.jpg', '/images/products/corp-gift-3-2.jpg', '/images/products/corp-gift-3-3.jpg'],
    category: 'Corporate Gifts',
    categorySlug: 'office-corporate-gifts',
    stock: 15,
    rating: 4.7,
    reviewCount: 42,
    featured: true,
    tags: ['gift-box', 'corporate', 'premium', 'gifting', 'new-arrival'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-corp-gift-4',
    name: 'Executive Leather Portfolio Set',
    slug: 'executive-leather-portfolio-set',
    description:
      'A premium full-grain leather portfolio with matching business card holder and pen loop. Features padded compartments for tablet and documents. Italian calfskin with hand-stitched edges. Available in cognac and black.',
    price: 950,
    compareAtPrice: 1150,
    images: ['/images/products/corp-gift-5.jpg', '/images/products/corp-gift-5-2.jpg', '/images/products/corp-gift-5-3.jpg'],
    category: 'Corporate Gifts',
    categorySlug: 'office-corporate-gifts',
    stock: 20,
    rating: 4.8,
    reviewCount: 38,
    featured: true,
    tags: ['leather', 'portfolio', 'corporate', 'executive', 'new-arrival'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-desk-1',
    name: 'Crystal Desk Organizer',
    slug: 'crystal-desk-organizer',
    description:
      'A stunning lead crystal desk organizer with multiple compartments for pens, cards, and paper clips. The hand-cut facets create a brilliant play of light. A sophisticated addition to any executive desk.',
    price: 680,
    compareAtPrice: null,
    images: ['/images/products/desk-1.jpg', '/images/products/desk-1-2.jpg', '/images/products/desk-1-3.jpg'],
    category: 'Desk Accessories',
    categorySlug: 'office-desk',
    stock: 12,
    rating: 4.7,
    reviewCount: 34,
    featured: true,
    tags: ['crystal', 'desk', 'organizer', 'executive'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-desk-2',
    name: 'Leather Desk Pad',
    slug: 'leather-desk-pad',
    description:
      'A generous full-grain Italian leather desk pad with felt backing and stitched edges. Available in cognac, black, and burgundy. Protects your desk while adding a touch of old-world sophistication. 90cm x 45cm.',
    price: 420,
    compareAtPrice: 520,
    images: ['/images/products/desk-2.jpg', '/images/products/desk-2-2.jpg', '/images/products/desk-2-3.jpg'],
    category: 'Desk Accessories',
    categorySlug: 'office-desk',
    stock: 20,
    rating: 4.8,
    reviewCount: 67,
    featured: true,
    tags: ['leather', 'desk-pad', 'italian', 'workspace'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-desk-3',
    name: 'Marble & Brass Desk Clock',
    slug: 'marble-brass-desk-clock',
    description:
      'An elegant desk clock combining Italian Carrara marble with brushed brass accents. The silent sweep movement ensures no ticking distraction. A statement piece for the discerning professional.',
    price: 580,
    compareAtPrice: null,
    images: ['/images/products/desk-4.jpg', '/images/products/desk-4-2.jpg', '/images/products/desk-4-3.jpg'],
    category: 'Desk Accessories',
    categorySlug: 'office-desk',
    stock: 10,
    rating: 4.9,
    reviewCount: 25,
    featured: true,
    tags: ['marble', 'brass', 'clock', 'desk', 'new-arrival'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-desk-4',
    name: 'Walnut Pen Holder Set',
    slug: 'walnut-pen-holder-set',
    description:
      'A handcrafted walnut wood pen holder with brass accents, paired with a matching letter tray. The warm wood grain and polished brass create a refined workspace aesthetic. Includes 2 brass-capped pens.',
    price: 340,
    compareAtPrice: 420,
    images: ['/images/products/desk-5.jpg', '/images/products/desk-5-2.jpg', '/images/products/desk-5-3.jpg'],
    category: 'Desk Accessories',
    categorySlug: 'office-desk',
    stock: 18,
    rating: 4.6,
    reviewCount: 44,
    featured: false,
    tags: ['walnut', 'pen-holder', 'brass', 'workspace'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-stationery-1',
    name: 'Premium Leather Journal',
    slug: 'premium-leather-journal',
    description:
      'A hand-stitched full-grain leather journal with 200 pages of fountain-pen-friendly cream paper. Features a wrap-around leather tie, gilt edges, and a ribbon bookmark. Acid-free 120gsm from an Italian mill.',
    price: 320,
    compareAtPrice: 400,
    images: ['/images/products/stationery-1.jpg', '/images/products/stationery-1-2.jpg', '/images/products/stationery-1-3.jpg'],
    category: 'Stationery',
    categorySlug: 'office-stationery',
    stock: 22,
    rating: 4.8,
    reviewCount: 73,
    featured: true,
    tags: ['journal', 'leather', 'hand-stitched', 'italian-paper'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-stationery-2',
    name: 'Gold Fountain Pen Set',
    slug: 'gold-fountain-pen-set',
    description:
      'A prestigious fountain pen and ballpoint pen set in solid brass with 24K gold plating. The fountain pen features a rhodium-plated 18K gold nib. Presented in a velvet-lined lacquer box. Engravable.',
    price: 1200,
    compareAtPrice: null,
    images: ['/images/products/stationery-2.jpg', '/images/products/stationery-2-2.jpg', '/images/products/stationery-2-3.jpg'],
    category: 'Stationery',
    categorySlug: 'office-stationery',
    stock: 8,
    rating: 4.9,
    reviewCount: 29,
    featured: true,
    tags: ['fountain-pen', 'gold', '24K', 'engravable'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-stationery-3',
    name: 'Crystal Inkwell & Pen Set',
    slug: 'crystal-inkwell-pen-set',
    description:
      'A magnificent hand-cut crystal inkwell paired with a matching dip pen featuring a gold-plated nib. The inkwell holds premium bottled ink and makes a stunning desk display piece. Gift boxed.',
    price: 890,
    compareAtPrice: 1050,
    images: ['/images/products/stationery-3.jpg', '/images/products/stationery-3-2.jpg', '/images/products/stationery-3-3.jpg'],
    category: 'Stationery',
    categorySlug: 'office-stationery',
    stock: 6,
    rating: 4.8,
    reviewCount: 19,
    featured: true,
    tags: ['crystal', 'inkwell', 'pen', 'desk', 'new-arrival'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-stationery-4',
    name: 'Artisan Wax Seal Letter Set',
    slug: 'artisan-wax-seal-letter-set',
    description:
      'A complete wax seal correspondence set featuring a brass seal with custom monogram, 3 sticks of premium wax, and 50 sheets of heavyweight laid paper with matching envelopes. The art of meaningful communication.',
    price: 280,
    compareAtPrice: null,
    images: ['/images/products/stationery-5.jpg', '/images/products/stationery-5-2.jpg', '/images/products/stationery-5-3.jpg'],
    category: 'Stationery',
    categorySlug: 'office-stationery',
    stock: 30,
    rating: 4.7,
    reviewCount: 51,
    featured: false,
    tags: ['wax-seal', 'letter', 'correspondence', 'monogram'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
]

const STATIC_NEW_ARRIVALS_PRODUCTS: StaticProduct[] = [
  {
    id: 'static-new-1',
    name: 'Smart Luxury Watch Gold Edition',
    slug: 'smart-luxury-watch-gold-edition',
    description:
      'The latest in luxury smartwatch technology. 18K rose gold case with sapphire crystal display, health monitoring suite, and 7-day battery life. Seamlessly blends traditional elegance with cutting-edge innovation.',
    price: 8500,
    compareAtPrice: 9800,
    images: ['/images/products/new-arrival-1.jpg', '/images/products/new-arrival-1-2.jpg', '/images/products/new-arrival-1-3.jpg'],
    category: 'New Arrivals',
    categorySlug: 'new-arrivals',
    stock: 10,
    rating: 4.9,
    reviewCount: 15,
    featured: true,
    tags: ['smart-watch', 'gold', 'luxury-tech', 'new-arrival'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '2-4 business days',
  },
  {
    id: 'static-new-2',
    name: 'Heritage Silk Scarf Collection',
    slug: 'heritage-silk-scarf-collection',
    description:
      "A limited-edition silk twill scarf featuring hand-painted heritage motifs. 100% Mulberry silk with hand-rolled edges. Each scarf comes numbered in a signature gift box. A collector's dream.",
    price: 680,
    compareAtPrice: null,
    images: ['/images/products/new-arrival-2.jpg', '/images/products/new-arrival-2-2.jpg', '/images/products/new-arrival-2-3.jpg'],
    category: 'New Arrivals',
    categorySlug: 'new-arrivals',
    stock: 25,
    rating: 4.8,
    reviewCount: 22,
    featured: true,
    tags: ['silk-scarf', 'heritage', 'limited-edition', 'new-arrival'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '2-4 business days',
  },
  {
    id: 'static-new-3',
    name: "Noir Oud Parfum Collector's Edition",
    slug: 'noir-oud-parfum-collectors-edition',
    description:
      "An exclusive collector's edition of our bestselling Noir Oud, presented in a hand-blown crystal flacon with 24K gold stopper. Notes of aged oud, Damask rose, and ambergris. Limited to 500 bottles worldwide.",
    price: 1200,
    compareAtPrice: null,
    images: ['/images/products/new-arrival-3.jpg', '/images/products/new-arrival-3-2.jpg', '/images/products/new-arrival-3-3.jpg'],
    category: 'New Arrivals',
    categorySlug: 'new-arrivals',
    stock: 5,
    rating: 5.0,
    reviewCount: 8,
    featured: true,
    tags: ['perfume', 'oud', 'collectors-edition', 'limited', 'new-arrival'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '2-4 business days',
  },
  {
    id: 'static-new-4',
    name: 'Artisan Gold Leaf Chocolate Box',
    slug: 'artisan-gold-leaf-chocolate-box',
    description:
      'A stunning box of 24 handcrafted chocolates, each adorned with edible gold leaf. Flavors include single-origin dark ganache, salted caramel, rose pistachio, and champagne truffle. Arrives in a velvet-lined box.',
    price: 450,
    compareAtPrice: 550,
    images: ['/images/products/new-arrival-4.jpg', '/images/products/new-arrival-4-2.jpg', '/images/products/new-arrival-4-3.jpg'],
    category: 'New Arrivals',
    categorySlug: 'new-arrivals',
    stock: 30,
    rating: 4.9,
    reviewCount: 34,
    featured: true,
    tags: ['chocolate', 'gold-leaf', 'artisan', 'gourmet', 'new-arrival'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '1-3 business days',
  },
  {
    id: 'static-new-5',
    name: 'Monogram Leather Card Holder',
    slug: 'monogram-leather-card-holder',
    description:
      'A sleek calfskin leather card holder with custom monogramming. Features 6 card slots, a central bill compartment, and RFID blocking technology. Available in 8 colors with gold or silver embossing.',
    price: 290,
    compareAtPrice: null,
    images: ['/images/products/new-arrival-5.jpg', '/images/products/new-arrival-5-2.jpg', '/images/products/new-arrival-5-3.jpg'],
    category: 'New Arrivals',
    categorySlug: 'new-arrivals',
    stock: 40,
    rating: 4.7,
    reviewCount: 61,
    featured: true,
    tags: ['card-holder', 'leather', 'monogram', 'RFID', 'new-arrival'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '2-4 business days',
  },
  {
    id: 'static-new-6',
    name: 'Crystal Decanter & Glasses Set',
    slug: 'crystal-decanter-glasses-set',
    description:
      "A hand-cut lead crystal decanter with matching set of 6 whiskey glasses. The intricate geometric cuts create a mesmerizing play of light. Perfect for the connoisseur's home bar. Gift boxed.",
    price: 1650,
    compareAtPrice: 1900,
    images: ['/images/products/new-arrival-6.jpg', '/images/products/new-arrival-6-2.jpg', '/images/products/new-arrival-6-3.jpg'],
    category: 'New Arrivals',
    categorySlug: 'new-arrivals',
    stock: 8,
    rating: 4.9,
    reviewCount: 17,
    featured: true,
    tags: ['crystal', 'decanter', 'whiskey', 'barware', 'new-arrival'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
]

const STATIC_KIDS_PRODUCTS: StaticProduct[] = [
  {
    id: 'static-kids-shirt-1',
    name: 'Classic Cotton Shirt (Ages 5-7)',
    slug: 'classic-cotton-shirt-5-7',
    description: 'A comfortable cotton shirt for young boys, perfect for school and casual wear. Features a button-down collar, chest pocket, and relaxed fit. Available in white, blue, and pink.',
    price: 450,
    compareAtPrice: 550,
    images: ['/images/products/kids-shirt-1.jpg', '/images/products/kids-shirt-1-2.jpg', '/images/products/kids-shirt-1-3.jpg'],
    category: 'Kids Shirts',
    categorySlug: 'kids-shirts',
    stock: 30,
    rating: 4.6,
    reviewCount: 42,
    featured: true,
    tags: ['shirt', 'cotton', 'boys', 'school', 'kids'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '2-4 business days',
  },
  {
    id: 'static-kids-shirt-2',
    name: 'Striped Formal Shirt (Ages 8-10)',
    slug: 'striped-formal-shirt-8-10',
    description: 'A smart striped formal shirt for growing boys. Slim fit with spread collar and adjustable cuffs. Perfect for school events and family gatherings. Available in navy/white and red/white stripes.',
    price: 520,
    compareAtPrice: null,
    images: ['/images/products/kids-shirt-2.jpg', '/images/products/kids-shirt-2-2.jpg', '/images/products/kids-shirt-2-3.jpg'],
    category: 'Kids Shirts',
    categorySlug: 'kids-shirts',
    stock: 25,
    rating: 4.7,
    reviewCount: 28,
    featured: true,
    tags: ['shirt', 'formal', 'striped', 'boys', 'kids'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '2-4 business days',
  },
  {
    id: 'static-kids-shirt-3',
    name: 'Denim Casual Shirt (Ages 11-13)',
    slug: 'denim-casual-shirt-11-13',
    description: 'A trendy denim casual shirt for pre-teens. Soft washed denim with button-down collar and dual chest pockets. Pairs perfectly with chinos or jeans.',
    price: 680,
    compareAtPrice: 800,
    images: ['/images/products/kids-shirt-3.jpg', '/images/products/kids-shirt-3-2.jpg', '/images/products/kids-shirt-3-3.jpg'],
    category: 'Kids Shirts',
    categorySlug: 'kids-shirts',
    stock: 20,
    rating: 4.8,
    reviewCount: 35,
    featured: true,
    tags: ['shirt', 'denim', 'casual', 'boys', 'pre-teen'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '2-4 business days',
  },
  {
    id: 'static-kids-shirt-4',
    name: 'Premium Linen Shirt (Ages 14-16)',
    slug: 'premium-linen-shirt-14-16',
    description: 'A premium linen shirt for teenagers who appreciate quality. Breathable fabric with a relaxed fit, mandarin collar, and coconut shell buttons. Available in sage, sky blue, and sand.',
    price: 890,
    compareAtPrice: null,
    images: ['/images/products/kids-shirt-4.jpg', '/images/products/kids-shirt-4-2.jpg', '/images/products/kids-shirt-4-3.jpg'],
    category: 'Kids Shirts',
    categorySlug: 'kids-shirts',
    stock: 15,
    rating: 4.9,
    reviewCount: 19,
    featured: true,
    tags: ['shirt', 'linen', 'premium', 'teen', 'boys'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '2-4 business days',
  },
  {
    id: 'static-kids-shirt-5',
    name: 'Oxford Button-Down Shirt (Ages 16-18)',
    slug: 'oxford-button-down-shirt-16-18',
    description: 'A classic Oxford button-down shirt for young adults. Premium cotton Oxford cloth with button-down collar, back box pleat, and barrel cuffs. Timeless style for college and beyond.',
    price: 950,
    compareAtPrice: 1100,
    images: ['/images/products/kids-shirt-5.jpg', '/images/products/kids-shirt-5-2.jpg', '/images/products/kids-shirt-5-3.jpg'],
    category: 'Kids Shirts',
    categorySlug: 'kids-shirts',
    stock: 12,
    rating: 4.8,
    reviewCount: 24,
    featured: false,
    tags: ['shirt', 'oxford', 'classic', 'young-adult', 'boys'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '2-4 business days',
  },
  {
    id: 'static-kids-dress-1',
    name: 'Floral Cotton Dress (Ages 5-7)',
    slug: 'floral-cotton-dress-5-7',
    description: 'A delightful floral cotton dress for little girls. Features a twirly skirt, Peter Pan collar, and back zip closure. Perfect for parties and playdates. Available in rose pink and lavender prints.',
    price: 550,
    compareAtPrice: 650,
    images: ['/images/products/kids-dress-1.jpg', '/images/products/kids-dress-1-2.jpg', '/images/products/kids-dress-1-3.jpg'],
    category: 'Kids Dresses',
    categorySlug: 'kids-dresses',
    stock: 28,
    rating: 4.7,
    reviewCount: 38,
    featured: true,
    tags: ['dress', 'floral', 'cotton', 'girls', 'party', 'kids'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '2-4 business days',
  },
  {
    id: 'static-kids-dress-2',
    name: 'Tulle Party Dress (Ages 8-10)',
    slug: 'tulle-party-dress-8-10',
    description: 'A magical tulle party dress for young girls. Layers of soft tulle over a satin bodice with delicate beadwork at the waist. Available in blush pink, champagne, and lilac.',
    price: 1200,
    compareAtPrice: null,
    images: ['/images/products/kids-dress-2.jpg', '/images/products/kids-dress-2-2.jpg', '/images/products/kids-dress-2-3.jpg'],
    category: 'Kids Dresses',
    categorySlug: 'kids-dresses',
    stock: 15,
    rating: 4.9,
    reviewCount: 22,
    featured: true,
    tags: ['dress', 'tulle', 'party', 'girls', 'special-occasion'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-kids-dress-3',
    name: 'Embroidered Anarkali Dress (Ages 11-13)',
    slug: 'embroidered-anarkali-dress-11-13',
    description: 'An elegant embroidered Anarkali dress for pre-teen girls. Features intricate thread embroidery on the yoke, flared silhouette, and matching dupatta. Perfect for festivals and celebrations.',
    price: 980,
    compareAtPrice: 1200,
    images: ['/images/products/kids-dress-3.jpg', '/images/products/kids-dress-3-2.jpg', '/images/products/kids-dress-3-3.jpg'],
    category: 'Kids Dresses',
    categorySlug: 'kids-dresses',
    stock: 18,
    rating: 4.8,
    reviewCount: 30,
    featured: true,
    tags: ['dress', 'anarkali', 'embroidered', 'girls', 'festival', 'pre-teen'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
  {
    id: 'static-kids-dress-4',
    name: 'Chic Shift Dress (Ages 14-16)',
    slug: 'chic-shift-dress-14-16',
    description: 'A sophisticated shift dress for teenage girls. A-line silhouette with V-neckline, side pockets, and back zip. Premium crepe fabric that drapes beautifully. Available in teal, burgundy, and black.',
    price: 1350,
    compareAtPrice: null,
    images: ['/images/products/kids-dress-4.jpg', '/images/products/kids-dress-4-2.jpg', '/images/products/kids-dress-4-3.jpg'],
    category: 'Kids Dresses',
    categorySlug: 'kids-dresses',
    stock: 14,
    rating: 4.7,
    reviewCount: 18,
    featured: true,
    tags: ['dress', 'shift', 'chic', 'teen', 'girls', 'crepe'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '2-4 business days',
  },
  {
    id: 'static-kids-dress-5',
    name: 'Silk Midi Dress (Ages 16-18)',
    slug: 'silk-midi-dress-16-18',
    description: 'An exquisite silk midi dress for young women. Features a wrap-style bodice, flutter sleeves, and a flowing midi-length skirt. Luxurious mulberry silk with subtle sheen. Perfect for special occasions and formals.',
    price: 2200,
    compareAtPrice: 2600,
    images: ['/images/products/kids-dress-5.jpg', '/images/products/kids-dress-5-2.jpg', '/images/products/kids-dress-5-3.jpg'],
    category: 'Kids Dresses',
    categorySlug: 'kids-dresses',
    stock: 8,
    rating: 4.9,
    reviewCount: 14,
    featured: false,
    tags: ['dress', 'silk', 'midi', 'young-adult', 'girls', 'formal'],
    platform: null,
    isExternal: false,
    sourceUrl: null,
    affiliateUrl: null,
    deliveryEstimate: '3-5 business days',
  },
]

/**
 * Look up a static product by its id.
 * Searches office, new-arrivals, and kids arrays.
 * Returns the simplified `StaticProduct` or `undefined` if not found.
 */
export function getStaticProductById(id: string): StaticProduct | undefined {
  return (
    STATIC_OFFICE_PRODUCTS.find((p) => p.id === id) ??
    STATIC_NEW_ARRIVALS_PRODUCTS.find((p) => p.id === id) ??
    STATIC_KIDS_PRODUCTS.find((p) => p.id === id)
  )
}

export function getStaticProductsByCategory(categorySlug: string): StaticProduct[] {
  return [
    ...STATIC_OFFICE_PRODUCTS,
    ...STATIC_NEW_ARRIVALS_PRODUCTS,
    ...STATIC_KIDS_PRODUCTS,
  ].filter((p) => p.categorySlug === categorySlug)
}

export function getAllStaticProducts(): StaticProduct[] {
  return [
    ...STATIC_OFFICE_PRODUCTS,
    ...STATIC_NEW_ARRIVALS_PRODUCTS,
    ...STATIC_KIDS_PRODUCTS,
  ]
}
