#!/usr/bin/env python3
"""
3 BOXES LUXURY - Technical Configuration Documentation
Complete step-by-step guide for Vercel deployment and configuration
"""

import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.platypus import (
    Paragraph, Spacer, Table, TableStyle, PageBreak, CondPageBreak,
    KeepTogether, HRFlowable
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.platypus import SimpleDocTemplate
import hashlib

# ─── Color Palette (auto-generated by pdf.py palette.generate) ───
ACCENT       = colors.HexColor('#c64f27')
TEXT_PRIMARY  = colors.HexColor('#242627')
TEXT_MUTED    = colors.HexColor('#7d848a')
BG_SURFACE   = colors.HexColor('#dadfe4')
BG_PAGE      = colors.HexColor('#eff1f3')

TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# ─── Font Registration ───
pdfmetrics.registerFont(TTFont('LibSerif', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LibSerif-Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('LibSans', '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LibSans-Bold', '/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))

registerFontFamily('LibSerif', normal='LibSerif', bold='LibSerif-Bold')
registerFontFamily('LibSans', normal='LibSans', bold='LibSans-Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

# ─── Page Setup ───
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 1.0 * inch
RIGHT_MARGIN = 1.0 * inch
TOP_MARGIN = 0.8 * inch
BOTTOM_MARGIN = 0.8 * inch
AVAILABLE_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ─── Styles ───
styles = getSampleStyleSheet()

title_style = ParagraphStyle(
    'DocTitle', fontName='LibSerif', fontSize=28, leading=34,
    textColor=ACCENT, alignment=TA_LEFT, spaceBefore=0, spaceAfter=12
)

h1_style = ParagraphStyle(
    'H1Custom', fontName='LibSerif', fontSize=20, leading=26,
    textColor=ACCENT, alignment=TA_LEFT, spaceBefore=18, spaceAfter=10
)

h2_style = ParagraphStyle(
    'H2Custom', fontName='LibSerif', fontSize=15, leading=20,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceBefore=14, spaceAfter=8
)

h3_style = ParagraphStyle(
    'H3Custom', fontName='LibSerif', fontSize=12, leading=16,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceBefore=10, spaceAfter=6
)

body_style = ParagraphStyle(
    'BodyCustom', fontName='LibSerif', fontSize=10.5, leading=16,
    textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceBefore=0, spaceAfter=6,
    firstLineIndent=0
)

code_style = ParagraphStyle(
    'CodeCustom', fontName='DejaVuSans', fontSize=9, leading=13,
    textColor=colors.HexColor('#1a1a2e'), alignment=TA_LEFT, spaceBefore=4, spaceAfter=4,
    leftIndent=12, backColor=colors.HexColor('#f4f4f8')
)

note_style = ParagraphStyle(
    'NoteCustom', fontName='LibSerif', fontSize=10, leading=14,
    textColor=colors.HexColor('#6b4c1e'), alignment=TA_LEFT, spaceBefore=6, spaceAfter=6,
    leftIndent=16, borderPadding=6, backColor=colors.HexColor('#fff8e7')
)

header_cell_style = ParagraphStyle(
    'HeaderCell', fontName='LibSerif', fontSize=10, leading=14,
    textColor=TABLE_HEADER_TEXT, alignment=TA_CENTER
)

cell_style = ParagraphStyle(
    'CellCustom', fontName='LibSerif', fontSize=9.5, leading=13,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT
)

cell_center_style = ParagraphStyle(
    'CellCenter', fontName='LibSerif', fontSize=9.5, leading=13,
    textColor=TEXT_PRIMARY, alignment=TA_CENTER
)

bullet_style = ParagraphStyle(
    'BulletCustom', fontName='LibSerif', fontSize=10.5, leading=16,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceBefore=2, spaceAfter=2,
    leftIndent=20, bulletIndent=8, bulletFontName='LibSerif',
    bulletFontSize=10.5
)

step_num_style = ParagraphStyle(
    'StepNum', fontName='LibSerif', fontSize=10.5, leading=16,
    textColor=ACCENT, alignment=TA_LEFT, spaceBefore=8, spaceAfter=4,
    leftIndent=8
)

toc_h1_style = ParagraphStyle(
    'TOCH1', fontName='LibSerif', fontSize=13, leading=20,
    leftIndent=20, textColor=TEXT_PRIMARY
)
toc_h2_style = ParagraphStyle(
    'TOCH2', fontName='LibSerif', fontSize=11, leading=18,
    leftIndent=40, textColor=TEXT_MUTED
)

# ─── Helper Functions ───
def make_table(data, col_widths=None):
    """Create a styled table."""
    if col_widths is None:
        col_widths = [AVAILABLE_WIDTH / len(data[0])] * len(data[0])
    else:
        total = sum(col_widths)
        if total < AVAILABLE_WIDTH * 0.85:
            scale = (AVAILABLE_WIDTH * 0.92) / total
            col_widths = [w * scale for w in col_widths]

    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_commands = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_commands.append(('BACKGROUND', (0, i), (-1, i), bg))

    t.setStyle(TableStyle(style_commands))
    return t

def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def step(number, text):
    return Paragraph('<b>Step %s:</b> %s' % (number, text), step_num_style)

def bullet(text):
    return Paragraph('<bullet>&bull;</bullet> %s' % text, bullet_style)

def code_block(text):
    return Paragraph(text, code_style)

def note(text):
    return Paragraph('<b>Note:</b> %s' % text, note_style)

def hr():
    return HRFlowable(width="100%", thickness=0.5, color=TEXT_MUTED, spaceAfter=8, spaceBefore=8)

# ─── TocDocTemplate ───
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

# ─── Build Document ───
output_path = '/home/z/my-project/3BOXES_LUXURY_Technical_Documentation.pdf'

doc = TocDocTemplate(
    output_path,
    pagesize=A4,
    leftMargin=LEFT_MARGIN,
    rightMargin=RIGHT_MARGIN,
    topMargin=TOP_MARGIN,
    bottomMargin=BOTTOM_MARGIN,
    title='3 BOXES LUXURY - Technical Configuration Documentation',
    author='Z.ai',
    creator='Z.ai',
    subject='Complete deployment and configuration guide for 3 BOXES LUXURY on Vercel'
)

story = []

# ─── Title Page Content ───
story.append(Spacer(1, 60))
story.append(Paragraph('<b>3 BOXES LUXURY</b>', title_style))
story.append(Spacer(1, 8))
story.append(Paragraph('Technical Configuration Documentation', ParagraphStyle(
    'SubTitle', fontName='LibSerif', fontSize=18, leading=24,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT
)))
story.append(Spacer(1, 6))
story.append(HRFlowable(width="40%", thickness=2, color=ACCENT, spaceAfter=16, spaceBefore=8))
story.append(Paragraph('Complete Step-by-Step Guide for Vercel Deployment,<br/>Database Configuration, and Shopify Integration', ParagraphStyle(
    'SubDesc', fontName='LibSerif', fontSize=12, leading=18,
    textColor=TEXT_MUTED, alignment=TA_LEFT
)))
story.append(Spacer(1, 40))

# Meta info table
meta_data = [
    [Paragraph('<b>Document</b>', header_cell_style), Paragraph('<b>Details</b>', header_cell_style)],
    [Paragraph('Project', cell_style), Paragraph('3 BOXES LUXURY - Luxury Gifting E-Commerce Platform', cell_style)],
    [Paragraph('Framework', cell_style), Paragraph('Next.js 16 with App Router (TypeScript)', cell_style)],
    [Paragraph('Deployment', cell_style), Paragraph('Vercel (Serverless)', cell_style)],
    [Paragraph('Live URL', cell_style), Paragraph('https://my-project-sepia-seven-42.vercel.app', cell_style)],
    [Paragraph('Database', cell_style), Paragraph('PostgreSQL (Neon) + SQLite (Local Dev)', cell_style)],
    [Paragraph('Commerce', cell_style), Paragraph('Shopify Headless Storefront', cell_style)],
    [Paragraph('Version', cell_style), Paragraph('1.0.0', cell_style)],
    [Paragraph('Date', cell_style), Paragraph('March 2025', cell_style)],
]
story.append(make_table(meta_data, [120, AVAILABLE_WIDTH - 120]))
story.append(Spacer(1, 30))
story.append(Paragraph('<b>CONFIDENTIAL</b> - This document contains sensitive credentials and API keys. Handle with care.', ParagraphStyle(
    'Confidential', fontName='LibSerif', fontSize=9, leading=12,
    textColor=colors.HexColor('#c0392b'), alignment=TA_CENTER
)))

story.append(PageBreak())

# ─── Table of Contents ───
toc = TableOfContents()
toc.levelStyles = [toc_h1_style, toc_h2_style]
story.append(Paragraph('<b>Table of Contents</b>', ParagraphStyle(
    'TOCTitle', fontName='LibSerif', fontSize=20, leading=26,
    textColor=ACCENT, alignment=TA_LEFT, spaceAfter=16
)))
story.append(toc)
story.append(PageBreak())

# ═══════════════════════════════════════════════════════════════════
# SECTION 1: PROJECT OVERVIEW
# ═══════════════════════════════════════════════════════════════════
story.append(add_heading('1. Project Overview', h1_style, level=0))
story.append(Paragraph(
    '3 BOXES LUXURY is a premium luxury gifting e-commerce platform built as a headless Shopify storefront. '
    'The application provides a complete shopping experience with product browsing, cart management, checkout, '
    'order tracking, corporate gifting portal, admin dashboard, AI-powered gift recommendations, multi-currency '
    'support, and internationalization (i18n) for 9 languages.',
    body_style
))
story.append(Spacer(1, 8))

story.append(add_heading('1.1 Technology Stack', h2_style, level=1))
stack_data = [
    [Paragraph('<b>Layer</b>', header_cell_style), Paragraph('<b>Technology</b>', header_cell_style), Paragraph('<b>Version</b>', header_cell_style)],
    [Paragraph('Framework', cell_style), Paragraph('Next.js (App Router)', cell_style), Paragraph('16.1.1', cell_center_style)],
    [Paragraph('Language', cell_style), Paragraph('TypeScript', cell_style), Paragraph('5.x', cell_center_style)],
    [Paragraph('Styling', cell_style), Paragraph('Tailwind CSS + shadcn/ui', cell_style), Paragraph('4.x', cell_center_style)],
    [Paragraph('ORM', cell_style), Paragraph('Prisma', cell_style), Paragraph('6.11.1', cell_center_style)],
    [Paragraph('State (Client)', cell_style), Paragraph('Zustand', cell_style), Paragraph('5.0.6', cell_center_style)],
    [Paragraph('State (Server)', cell_style), Paragraph('TanStack React Query', cell_style), Paragraph('5.82.0', cell_center_style)],
    [Paragraph('Auth', cell_style), Paragraph('NextAuth.js (Custom JWT)', cell_style), Paragraph('4.24.11', cell_center_style)],
    [Paragraph('Animations', cell_style), Paragraph('Framer Motion', cell_style), Paragraph('12.23.2', cell_center_style)],
    [Paragraph('Charts', cell_style), Paragraph('Recharts', cell_style), Paragraph('2.15.4', cell_center_style)],
    [Paragraph('Database (Prod)', cell_style), Paragraph('PostgreSQL (Neon)', cell_style), Paragraph('-', cell_center_style)],
    [Paragraph('Database (Dev)', cell_style), Paragraph('SQLite', cell_style), Paragraph('-', cell_center_style)],
    [Paragraph('Commerce', cell_style), Paragraph('Shopify Admin API + Storefront API', cell_style), Paragraph('2024-10', cell_center_style)],
    [Paragraph('Deployment', cell_style), Paragraph('Vercel (Serverless Functions)', cell_style), Paragraph('-', cell_center_style)],
    [Paragraph('Package Manager', cell_style), Paragraph('Bun', cell_style), Paragraph('-', cell_center_style)],
]
story.append(Spacer(1, 6))
story.append(make_table(stack_data, [120, 240, 80]))

story.append(Spacer(1, 12))
story.append(add_heading('1.2 Application Architecture', h2_style, level=1))
story.append(Paragraph(
    'The application follows a headless commerce architecture where Shopify serves as the product and inventory '
    'backend, while the Next.js application handles the storefront UI, user authentication, cart management, '
    'order processing, and corporate gifting workflows. A Shopify Admin API fallback layer ensures products '
    'and categories are always available even when the PostgreSQL database is unreachable.',
    body_style
))

arch_data = [
    [Paragraph('<b>Component</b>', header_cell_style), Paragraph('<b>Role</b>', header_cell_style)],
    [Paragraph('Next.js Frontend', cell_style), Paragraph('Server-side rendered UI with client-side hydration', cell_style)],
    [Paragraph('API Routes (/api/*)', cell_style), Paragraph('RESTful backend endpoints for all business logic', cell_style)],
    [Paragraph('Prisma ORM', cell_style), Paragraph('Database abstraction layer (SQLite local / PostgreSQL prod)', cell_style)],
    [Paragraph('Shopify Admin API', cell_style), Paragraph('Primary product/category data source with fallback caching', cell_style)],
    [Paragraph('Shopify Storefront API', cell_style), Paragraph('Checkout and cart integration with Shopify', cell_style)],
    [Paragraph('Vercel Serverless', cell_style), Paragraph('Deployment platform with edge functions and CDN', cell_style)],
    [Paragraph('Neon PostgreSQL', cell_style), Paragraph('Serverless PostgreSQL for production data persistence', cell_style)],
]
story.append(Spacer(1, 6))
story.append(make_table(arch_data, [160, AVAILABLE_WIDTH - 160]))

story.append(Spacer(1, 12))
story.append(add_heading('1.3 Current Deployment Status', h2_style, level=1))

status_data = [
    [Paragraph('<b>Feature</b>', header_cell_style), Paragraph('<b>Status</b>', header_cell_style), Paragraph('<b>Notes</b>', header_cell_style)],
    [Paragraph('Frontend UI', cell_style), Paragraph('WORKING', cell_style), Paragraph('All pages render correctly', cell_style)],
    [Paragraph('Products (57 items)', cell_style), Paragraph('WORKING', cell_style), Paragraph('Via Shopify Admin API fallback', cell_style)],
    [Paragraph('Categories (15 items)', cell_style), Paragraph('WORKING', cell_style), Paragraph('Derived from Shopify collections', cell_style)],
    [Paragraph('Shopping Cart', cell_style), Paragraph('NEEDS DB', cell_style), Paragraph('Requires PostgreSQL connection', cell_style)],
    [Paragraph('Orders', cell_style), Paragraph('NEEDS DB', cell_style), Paragraph('Requires PostgreSQL connection', cell_style)],
    [Paragraph('User Authentication', cell_style), Paragraph('NEEDS DB', cell_style), Paragraph('Requires PostgreSQL connection', cell_style)],
    [Paragraph('Admin Dashboard', cell_style), Paragraph('NEEDS DB', cell_style), Paragraph('Requires PostgreSQL connection', cell_style)],
    [Paragraph('Corporate Gifting', cell_style), Paragraph('NEEDS DB', cell_style), Paragraph('Requires PostgreSQL connection', cell_style)],
    [Paragraph('AI Recommendations', cell_style), Paragraph('NEEDS DB', cell_style), Paragraph('Requires PostgreSQL connection', cell_style)],
    [Paragraph('Multi-Currency', cell_style), Paragraph('PARTIAL', cell_style), Paragraph('Config exists, needs DB for rates', cell_style)],
    [Paragraph('i18n (9 languages)', cell_style), Paragraph('WORKING', cell_style), Paragraph('Translation files embedded', cell_style)],
]
story.append(Spacer(1, 6))
story.append(make_table(status_data, [140, 80, AVAILABLE_WIDTH - 220]))

# ═══════════════════════════════════════════════════════════════════
# SECTION 2: VERCEL DEPLOYMENT GUIDE
# ═══════════════════════════════════════════════════════════════════
story.append(Spacer(1, 18))
story.append(add_heading('2. Vercel Deployment - Step by Step', h1_style, level=0))

story.append(add_heading('2.1 Prerequisites', h2_style, level=1))
story.append(bullet('Node.js 18+ or Bun runtime installed'))
story.append(bullet('A Vercel account (free tier works)'))
story.append(bullet('Vercel CLI installed: npm i -g vercel'))
story.append(bullet('A Neon PostgreSQL database (free tier works)'))
story.append(bullet('Shopify Partner account with store access'))
story.append(bullet('Git repository with the project code'))

story.append(Spacer(1, 8))
story.append(add_heading('2.2 Vercel Account Setup', h2_style, level=1))
story.append(step('1', 'Go to https://vercel.com and sign up or log in'))
story.append(step('2', 'Connect your Git provider (GitHub/GitLab/Bitbucket)'))
story.append(step('3', 'Install the Vercel CLI globally:'))
story.append(code_block('npm install -g vercel'))
story.append(step('4', 'Login to Vercel from CLI:'))
story.append(code_block('vercel login'))
story.append(step('5', 'Verify login:'))
story.append(code_block('vercel whoami'))

story.append(Spacer(1, 8))
story.append(add_heading('2.3 Project Deployment', h2_style, level=1))
story.append(step('1', 'Navigate to the project directory:'))
story.append(code_block('cd /home/z/my-project'))
story.append(step('2', 'Link the project to Vercel (first time only):'))
story.append(code_block('vercel link'))
story.append(Paragraph(
    'When prompted, select your team/scope and accept the default project name or provide a custom one.',
    body_style
))
story.append(step('3', 'Deploy to preview:'))
story.append(code_block('vercel'))
story.append(step('4', 'Deploy to production:'))
story.append(code_block('vercel --prod'))
story.append(note('The vercel-build script in package.json automatically switches Prisma from SQLite to PostgreSQL and runs prisma db push before building.'))

story.append(Spacer(1, 8))
story.append(add_heading('2.4 Vercel Build Configuration', h2_style, level=1))
story.append(Paragraph('The project uses a custom vercel.json file that controls the build process:', body_style))
story.append(Spacer(1, 4))

vconfig_data = [
    [Paragraph('<b>Setting</b>', header_cell_style), Paragraph('<b>Value</b>', header_cell_style), Paragraph('<b>Purpose</b>', header_cell_style)],
    [Paragraph('buildCommand', cell_style), Paragraph('sed + prisma generate +<br/>prisma db push + next build', cell_style), Paragraph('Switches SQLite to PostgreSQL,<br/>generates Prisma client, pushes<br/>schema, then builds', cell_style)],
    [Paragraph('installCommand', cell_style), Paragraph('bun install', cell_style), Paragraph('Uses Bun for faster installs', cell_style)],
    [Paragraph('framework', cell_style), Paragraph('nextjs', cell_style), Paragraph('Auto-detected Next.js framework', cell_style)],
    [Paragraph('regions', cell_style), Paragraph('bom1 (Mumbai)', cell_style), Paragraph('Deployed to Mumbai region<br/>for India-based audience', cell_style)],
]
story.append(make_table(vconfig_data, [100, 180, AVAILABLE_WIDTH - 280]))

story.append(Spacer(1, 8))
story.append(add_heading('2.5 Build Script Details', h2_style, level=1))
story.append(Paragraph(
    'The vercel-build script in package.json performs the following operations in sequence:',
    body_style
))
story.append(Spacer(1, 4))

build_steps = [
    [Paragraph('<b>Step</b>', header_cell_style), Paragraph('<b>Command</b>', header_cell_style), Paragraph('<b>Description</b>', header_cell_style)],
    [Paragraph('1', cell_center_style), Paragraph("sed -i 's/provider = \"sqlite\"/<br/>provider = \"postgresql\"/g' prisma/schema.prisma", cell_style), Paragraph('Switches Prisma datasource from SQLite to PostgreSQL for production', cell_style)],
    [Paragraph('2', cell_center_style), Paragraph('prisma generate', cell_style), Paragraph('Generates Prisma Client with PostgreSQL provider', cell_style)],
    [Paragraph('3', cell_center_style), Paragraph('prisma db push --accept-data-loss', cell_style), Paragraph('Pushes schema to Neon PostgreSQL and creates tables', cell_style)],
    [Paragraph('4', cell_center_style), Paragraph('next build', cell_style), Paragraph('Builds the Next.js application for production', cell_style)],
]
story.append(make_table(build_steps, [40, 220, AVAILABLE_WIDTH - 260]))

story.append(note('The --accept-data-loss flag is used because schema changes in development may not be backward-compatible. In production, use prisma migrate for safer migrations.'))

# ═══════════════════════════════════════════════════════════════════
# SECTION 3: ENVIRONMENT VARIABLES
# ═══════════════════════════════════════════════════════════════════
story.append(Spacer(1, 18))
story.append(add_heading('3. Environment Variables Configuration', h1_style, level=0))

story.append(Paragraph(
    'Environment variables are the most critical part of the deployment. They must be configured correctly '
    'on Vercel for the application to function properly. Below is the complete list of required environment '
    'variables with their current values and descriptions.',
    body_style
))

story.append(Spacer(1, 8))
story.append(add_heading('3.1 Required Environment Variables', h2_style, level=1))

env_data = [
    [Paragraph('<b>Variable</b>', header_cell_style), Paragraph('<b>Value</b>', header_cell_style), Paragraph('<b>Required</b>', header_cell_style)],
    [Paragraph('DATABASE_URL', cell_style), Paragraph('postgresql://user:pass@ep-xxx.<br/>neon.tech/dbname?sslmode=require', cell_style), Paragraph('YES', cell_center_style)],
    [Paragraph('SHOPIFY_STORE_DOMAIN', cell_style), Paragraph('3boxesluxury-2.myshopify.com', cell_style), Paragraph('YES', cell_center_style)],
    [Paragraph('SHOPIFY_STOREFRONT_ACCESS_TOKEN', cell_style), Paragraph('09124abbd07ca423DB9488B3DC2C737F', cell_style), Paragraph('YES', cell_center_style)],
    [Paragraph('SHOPIFY_ADMIN_API_TOKEN', cell_style), Paragraph('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', cell_style), Paragraph('YES', cell_center_style)],
    [Paragraph('NEXTAUTH_SECRET', cell_style), Paragraph('(auto-generated or custom)', cell_style), Paragraph('YES', cell_center_style)],
    [Paragraph('NEXTAUTH_URL', cell_style), Paragraph('https://my-project-sepia-seven-42.vercel.app', cell_style), Paragraph('YES', cell_center_style)],
]
story.append(make_table(env_data, [180, 200, 60]))

story.append(Spacer(1, 8))
story.append(add_heading('3.2 Setting Environment Variables on Vercel', h2_style, level=1))
story.append(step('1', 'Go to your Vercel Dashboard: https://vercel.com/dashboard'))
story.append(step('2', 'Select your project (3 BOXES LUXURY)'))
story.append(step('3', 'Navigate to Settings > Environment Variables'))
story.append(step('4', 'Add each variable one by one:'))
story.append(Spacer(1, 4))
story.append(Paragraph(
    'For each variable, enter the Name and Value, then select the environments '
    '(Production, Preview, Development) where it should be available.',
    body_style
))
story.append(step('5', 'Alternatively, use the Vercel CLI to set environment variables:'))
story.append(code_block('vercel env add DATABASE_URL production'))
story.append(code_block('vercel env add SHOPIFY_STORE_DOMAIN production'))
story.append(code_block('vercel env add SHOPIFY_ADMIN_API_TOKEN production'))
story.append(code_block('vercel env add SHOPIFY_STOREFRONT_ACCESS_TOKEN production'))
story.append(step('6', 'Or set all at once using the Vercel API:'))
story.append(code_block('vercel --prod -e DATABASE_URL="your_neon_connection_string"'))

story.append(Spacer(1, 8))
story.append(add_heading('3.3 Variable Details', h2_style, level=1))

story.append(Paragraph('<b>DATABASE_URL</b>', h3_style))
story.append(Paragraph(
    'The PostgreSQL connection string for Neon. This is the ONLY variable that needs to be updated '
    'to make the full application functional. Currently set to a placeholder value. The format is:',
    body_style
))
story.append(code_block('postgresql://[user]:[password]@[endpoint].neon.tech/[dbname]?sslmode=require'))
story.append(note('The DATABASE_URL must point to a real Neon PostgreSQL database. The current placeholder value will cause all database-dependent features to fail.'))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>SHOPIFY_STORE_DOMAIN</b>', h3_style))
story.append(Paragraph(
    'Your Shopify store domain. This is used by both the Storefront API and Admin API to construct '
    'the base URL for API calls. Format: your-store.myshopify.com',
    body_style
))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>SHOPIFY_STOREFRONT_ACCESS_TOKEN</b>', h3_style))
story.append(Paragraph(
    'The Storefront API access token created in your Shopify Admin under Apps > Develop apps. '
    'This token is used for storefront operations like product queries and checkout creation. '
    'Current value: 09124abbd07ca423DB9488B3DC2C737F',
    body_style
))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>SHOPIFY_ADMIN_API_TOKEN</b>', h3_style))
story.append(Paragraph(
    'The Admin API access token (starts with shpat_). This token is used for the fallback data '
    'fetching system that keeps products and categories available even when the database is down. '
    'Current value: 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',
    body_style
))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>NEXTAUTH_SECRET</b>', h3_style))
story.append(Paragraph(
    'A secret key used by NextAuth.js for encryption and signing. Generate one with:',
    body_style
))
story.append(code_block('openssl rand -base64 32'))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>NEXTAUTH_URL</b>', h3_style))
story.append(Paragraph(
    'The canonical URL of your deployed application. This is used by NextAuth.js for callback URLs. '
    'Set this to your Vercel deployment URL: https://my-project-sepia-seven-42.vercel.app',
    body_style
))

# ═══════════════════════════════════════════════════════════════════
# SECTION 4: NEON POSTGRESQL DATABASE SETUP
# ═══════════════════════════════════════════════════════════════════
story.append(Spacer(1, 18))
story.append(add_heading('4. Neon PostgreSQL Database Setup', h1_style, level=0))

story.append(Paragraph(
    'Neon is a serverless PostgreSQL platform that provides free-tier databases perfect for Vercel deployments. '
    'This section walks you through creating a Neon database and connecting it to your Vercel project.',
    body_style
))

story.append(Spacer(1, 8))
story.append(add_heading('4.1 Creating a Neon Database', h2_style, level=1))
story.append(step('1', 'Go to https://console.neon.tech and sign up (free with GitHub/Google/Email)'))
story.append(step('2', 'Click "Create Project" or "New Project"'))
story.append(step('3', 'Configure the project:'))

neon_config = [
    [Paragraph('<b>Setting</b>', header_cell_style), Paragraph('<b>Recommended Value</b>', header_cell_style)],
    [Paragraph('Project Name', cell_style), Paragraph('3boxes-luxury', cell_style)],
    [Paragraph('Region', cell_style), Paragraph('Asia (Mumbai / Singapore)', cell_style)],
    [Paragraph('PostgreSQL Version', cell_style), Paragraph('16 (latest stable)', cell_style)],
    [Paragraph('Database Name', cell_style), Paragraph('boxes_luxury', cell_style)],
    [Paragraph('Branch', cell_style), Paragraph('main (default)', cell_style)],
]
story.append(make_table(neon_config, [160, AVAILABLE_WIDTH - 160]))

story.append(step('4', 'Click "Create Project" and wait for provisioning (usually 10-30 seconds)'))
story.append(step('5', 'Once created, you will see the connection string on the dashboard'))
story.append(step('6', 'Copy the connection string - it looks like:'))
story.append(code_block('postgresql://neondb_owner:AbCdEfGh@ep-cool-name-123456.us-east-2.aws.neon.tech/boxes_luxury?sslmode=require'))
story.append(note('Save this connection string securely. You will need it for the DATABASE_URL environment variable on Vercel.'))

story.append(Spacer(1, 8))
story.append(add_heading('4.2 Neon Free Tier Limits', h2_style, level=1))
neon_limits = [
    [Paragraph('<b>Resource</b>', header_cell_style), Paragraph('<b>Free Tier Limit</b>', header_cell_style)],
    [Paragraph('Storage', cell_style), Paragraph('0.5 GB', cell_style)],
    [Paragraph('Compute', cell_style), Paragraph('300 hours/month (auto-suspend)', cell_style)],
    [Paragraph('Branches', cell_style), Paragraph('10 branches', cell_style)],
    [Paragraph('Projects', cell_style), Paragraph('1 project', cell_style)],
    [Paragraph('Rows', cell_style), Paragraph('Unlimited (within storage)', cell_style)],
    [Paragraph('Connections', cell_style), Paragraph('Via connection pooling', cell_style)],
]
story.append(make_table(neon_limits, [160, AVAILABLE_WIDTH - 160]))

story.append(Spacer(1, 8))
story.append(add_heading('4.3 Connecting Neon to Vercel', h2_style, level=1))
story.append(Paragraph(
    'Once you have the Neon connection string, update the DATABASE_URL on Vercel:',
    body_style
))
story.append(Spacer(1, 4))

story.append(Paragraph('<b>Method 1: Via Vercel Dashboard</b>', h3_style))
story.append(step('1', 'Go to https://vercel.com/dashboard'))
story.append(step('2', 'Select your project'))
story.append(step('3', 'Navigate to Settings > Environment Variables'))
story.append(step('4', 'Find DATABASE_URL and click Edit'))
story.append(step('5', 'Replace the placeholder with your Neon connection string'))
story.append(step('6', 'Save and redeploy (Deployments > Redeploy)'))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>Method 2: Via Vercel CLI</b>', h3_style))
story.append(code_block('# Remove old value'))
story.append(code_block('vercel env rm DATABASE_URL production'))
story.append(code_block('# Add new value'))
story.append(code_block('vercel env add DATABASE_URL production'))
story.append(code_block('# Paste your Neon connection string when prompted'))
story.append(code_block('# Redeploy'))
story.append(code_block('vercel --prod'))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>Method 3: Using Neon-Vercel Integration (Recommended)</b>', h3_style))
story.append(step('1', 'Go to https://vercel.com/integrations/neon'))
story.append(step('2', 'Click "Add Integration"'))
story.append(step('3', 'Select your Vercel project'))
story.append(step('4', 'This automatically creates a Neon database and sets DATABASE_URL, POSTGRES_URL, and POSTGRES_PRISMA_URL environment variables'))
story.append(step('5', 'Redeploy your project'))
story.append(note('The Neon-Vercel integration is the easiest method. It also sets POSTGRES_PRISMA_URL which is used by the vercel.json build command for prisma db push.'))

story.append(Spacer(1, 8))
story.append(add_heading('4.4 Verifying Database Connection', h2_style, level=1))
story.append(Paragraph(
    'After updating DATABASE_URL and redeploying, verify the database connection by checking these API endpoints:',
    body_style
))
story.append(Spacer(1, 4))

verify_data = [
    [Paragraph('<b>Endpoint</b>', header_cell_style), Paragraph('<b>Method</b>', header_cell_style), Paragraph('<b>Expected Result</b>', header_cell_style)],
    [Paragraph('/api/products', cell_style), Paragraph('GET', cell_center_style), Paragraph('Returns product list (Shopify fallback or DB)', cell_style)],
    [Paragraph('/api/categories', cell_style), Paragraph('GET', cell_center_style), Paragraph('Returns category list', cell_style)],
    [Paragraph('/api/cart', cell_style), Paragraph('GET', cell_center_style), Paragraph('Returns cart data (needs DB)', cell_style)],
    [Paragraph('/api/auth/me', cell_style), Paragraph('GET', cell_center_style), Paragraph('Returns current user (needs DB)', cell_style)],
    [Paragraph('/api/admin/stats', cell_style), Paragraph('GET', cell_center_style), Paragraph('Returns admin dashboard stats (needs DB)', cell_style)],
]
story.append(make_table(verify_data, [120, 60, AVAILABLE_WIDTH - 180]))

# ═══════════════════════════════════════════════════════════════════
# SECTION 5: SHOPIFY CONFIGURATION
# ═══════════════════════════════════════════════════════════════════
story.append(Spacer(1, 18))
story.append(add_heading('5. Shopify Integration Configuration', h1_style, level=0))

story.append(Paragraph(
    'The application integrates with Shopify through two APIs: the Admin API (for product/category data fallback) '
    'and the Storefront API (for checkout and cart functionality). This section details the complete Shopify setup.',
    body_style
))

story.append(Spacer(1, 8))
story.append(add_heading('5.1 Shopify Store Details', h2_style, level=1))
shopify_data = [
    [Paragraph('<b>Property</b>', header_cell_style), Paragraph('<b>Value</b>', header_cell_style)],
    [Paragraph('Store Domain', cell_style), Paragraph('3boxesluxury-2.myshopify.com', cell_style)],
    [Paragraph('Shopify Admin URL', cell_style), Paragraph('https://3boxesluxury-2.myshopify.com/admin', cell_style)],
    [Paragraph('API Version', cell_style), Paragraph('2024-10', cell_style)],
    [Paragraph('Admin API Token', cell_style), Paragraph('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', cell_style)],
    [Paragraph('Storefront API Token', cell_style), Paragraph('09124abbd07ca423DB9488B3DC2C737F', cell_style)],
    [Paragraph('Total Products', cell_style), Paragraph('57 (active)', cell_style)],
    [Paragraph('Total Collections', cell_style), Paragraph('15 (custom + smart)', cell_style)],
]
story.append(make_table(shopify_data, [160, AVAILABLE_WIDTH - 160]))

story.append(Spacer(1, 8))
story.append(add_heading('5.2 Creating Shopify API Credentials', h2_style, level=1))
story.append(Paragraph(
    'If you need to regenerate or create new API credentials, follow these steps:',
    body_style
))
story.append(step('1', 'Log into Shopify Admin: https://3boxesluxury-2.myshopify.com/admin'))
story.append(step('2', 'Navigate to Apps > Develop apps (in the left sidebar)'))
story.append(step('3', 'Click "Create an app"'))
story.append(step('4', 'Name the app (e.g., "3 Boxes Luxury Headless") and click Create'))
story.append(step('5', 'Go to Configuration > Configure Admin API Scopes'))
story.append(step('6', 'Enable the following scopes:'))

scopes_data = [
    [Paragraph('<b>Scope</b>', header_cell_style), Paragraph('<b>Access Level</b>', header_cell_style), Paragraph('<b>Purpose</b>', header_cell_style)],
    [Paragraph('read_products', cell_style), Paragraph('Read', cell_center_style), Paragraph('Fetch product data', cell_style)],
    [Paragraph('read_product_listings', cell_style), Paragraph('Read', cell_center_style), Paragraph('Fetch product listings', cell_style)],
    [Paragraph('read_custom_collections', cell_style), Paragraph('Read', cell_center_style), Paragraph('Fetch custom collections', cell_style)],
    [Paragraph('read_smart_collections', cell_style), Paragraph('Read', cell_center_style), Paragraph('Fetch smart collections', cell_style)],
    [Paragraph('read_inventory', cell_style), Paragraph('Read', cell_center_style), Paragraph('Check stock levels', cell_style)],
    [Paragraph('read_orders', cell_style), Paragraph('Read', cell_center_style), Paragraph('Sync order data', cell_style)],
    [Paragraph('read_customers', cell_style), Paragraph('Read', cell_center_style), Paragraph('Customer data sync', cell_style)],
    [Paragraph('read_price_rules', cell_style), Paragraph('Read', cell_center_style), Paragraph('Fetch discount rules', cell_style)],
]
story.append(make_table(scopes_data, [160, 80, AVAILABLE_WIDTH - 240]))

story.append(step('7', 'Click Save and then "Install app" to generate the Admin API token'))
story.append(step('8', 'Copy the token (starts with shpat_) - it is shown only once'))
story.append(step('9', 'For Storefront API: Go to Configuration > Storefront API'))
story.append(step('10', 'Enable the Storefront API and select the required scopes'))
story.append(step('11', 'Copy the Storefront API access token'))

story.append(Spacer(1, 8))
story.append(add_heading('5.3 Shopify API Fallback System', h2_style, level=1))
story.append(Paragraph(
    'The application implements a fallback system in src/lib/shopify.ts that uses the Shopify Admin API '
    'to fetch products and categories when the PostgreSQL database is unavailable. Key features include:',
    body_style
))
story.append(bullet('In-memory caching with 5-minute TTL (CACHE_TTL = 5 * 60 * 1000)'))
story.append(bullet('Next.js revalidation at 300 seconds (5 minutes)'))
story.append(bullet('Fetches up to 250 products per API call'))
story.append(bullet('Derives categories from both Shopify collections and product types'))
story.append(bullet('Search functionality filtering by name, description, and tags'))
story.append(bullet('Auto-maps Shopify product_type to application category slugs'))
story.append(note('Products fetched via the fallback have IDs prefixed with "shopify-" (e.g., shopify-123456789) to distinguish them from database-sourced products.'))

# ═══════════════════════════════════════════════════════════════════
# SECTION 6: DATABASE SCHEMA
# ═══════════════════════════════════════════════════════════════════
story.append(Spacer(1, 18))
story.append(add_heading('6. Database Schema (Prisma)', h1_style, level=0))

story.append(Paragraph(
    'The application uses Prisma ORM with 35+ models covering e-commerce, corporate gifting, '
    'inventory management, accounting, and more. The schema is defined in prisma/schema.prisma and '
    'automatically pushed to the database during the Vercel build process.',
    body_style
))

story.append(Spacer(1, 8))
story.append(add_heading('6.1 Core E-Commerce Models', h2_style, level=1))
models_ecom = [
    [Paragraph('<b>Model</b>', header_cell_style), Paragraph('<b>Purpose</b>', header_cell_style), Paragraph('<b>Key Fields</b>', header_cell_style)],
    [Paragraph('Category', cell_style), Paragraph('Product categories', cell_style), Paragraph('name, slug, description, image', cell_style)],
    [Paragraph('Product', cell_style), Paragraph('Product catalog', cell_style), Paragraph('name, slug, price, images, stock, featured', cell_style)],
    [Paragraph('ProductVariant', cell_style), Paragraph('Product variants', cell_style), Paragraph('name, sku, price, stock, attributes', cell_style)],
    [Paragraph('ProductImage', cell_style), Paragraph('Product images', cell_style), Paragraph('url, alt, sort order', cell_style)],
    [Paragraph('Cart', cell_style), Paragraph('Shopping cart', cell_style), Paragraph('sessionId, userId, couponCode', cell_style)],
    [Paragraph('CartItem', cell_style), Paragraph('Cart line items', cell_style), Paragraph('quantity, variantId, giftWrapping', cell_style)],
    [Paragraph('Order', cell_style), Paragraph('Customer orders', cell_style), Paragraph('orderNumber, total, status, trackingNumber', cell_style)],
    [Paragraph('OrderItem', cell_style), Paragraph('Order line items', cell_style), Paragraph('name, price, quantity, giftWrapping', cell_style)],
    [Paragraph('Review', cell_style), Paragraph('Product reviews', cell_style), Paragraph('rating, title, comment, verified', cell_style)],
    [Paragraph('WishlistItem', cell_style), Paragraph('User wishlist', cell_style), Paragraph('userId, productId', cell_style)],
]
story.append(make_table(models_ecom, [100, 130, AVAILABLE_WIDTH - 230]))

story.append(Spacer(1, 8))
story.append(add_heading('6.2 User and Authentication Models', h2_style, level=1))
models_auth = [
    [Paragraph('<b>Model</b>', header_cell_style), Paragraph('<b>Purpose</b>', header_cell_style), Paragraph('<b>Key Fields</b>', header_cell_style)],
    [Paragraph('User', cell_style), Paragraph('User accounts', cell_style), Paragraph('email, name, role, adminRole, twoFactorEnabled', cell_style)],
    [Paragraph('Session', cell_style), Paragraph('Auth sessions', cell_style), Paragraph('token, userId, expiresAt, deviceInfo', cell_style)],
    [Paragraph('UserPermission', cell_style), Paragraph('Role permissions', cell_style), Paragraph('userId, permission', cell_style)],
    [Paragraph('AuditLog', cell_style), Paragraph('Activity audit', cell_style), Paragraph('action, entity, ipAddress', cell_style)],
]
story.append(make_table(models_auth, [100, 130, AVAILABLE_WIDTH - 230]))

story.append(Spacer(1, 8))
story.append(add_heading('6.3 Corporate Gifting Models', h2_style, level=1))
models_corp = [
    [Paragraph('<b>Model</b>', header_cell_style), Paragraph('<b>Purpose</b>', header_cell_style), Paragraph('<b>Key Fields</b>', header_cell_style)],
    [Paragraph('CorporateAccount', cell_style), Paragraph('Corporate accounts', cell_style), Paragraph('companyName, approvalStatus, creditLimit, discountPercent', cell_style)],
    [Paragraph('CorporateMember', cell_style), Paragraph('Team members', cell_style), Paragraph('email, role, status', cell_style)],
    [Paragraph('CorporateBranding', cell_style), Paragraph('Branding config', cell_style), Paragraph('logoUrl, primaryColor, packagingType', cell_style)],
    [Paragraph('CorporateCampaign', cell_style), Paragraph('Gifting campaigns', cell_style), Paragraph('name, occasion, budget, status', cell_style)],
    [Paragraph('CampaignRecipient', cell_style), Paragraph('Recipients', cell_style), Paragraph('name, email, giftStatus, orderId', cell_style)],
]
story.append(make_table(models_corp, [120, 130, AVAILABLE_WIDTH - 250]))

story.append(Spacer(1, 8))
story.append(add_heading('6.4 Admin and Operations Models', h2_style, level=1))
models_admin = [
    [Paragraph('<b>Model</b>', header_cell_style), Paragraph('<b>Purpose</b>', header_cell_style)],
    [Paragraph('Vendor', cell_style), Paragraph('Product vendors and suppliers', cell_style)],
    [Paragraph('Invoice / InvoiceItem', cell_style), Paragraph('Vendor invoices and line items', cell_style)],
    [Paragraph('AccountEntry', cell_style), Paragraph('Double-entry accounting (debit/credit)', cell_style)],
    [Paragraph('InventoryLog', cell_style), Paragraph('Stock movement tracking', cell_style)],
    [Paragraph('Offer', cell_style), Paragraph('Discount codes and promotional offers', cell_style)],
    [Paragraph('PaymentSession', cell_style), Paragraph('Payment gateway sessions (Razorpay/Stripe)', cell_style)],
    [Paragraph('OrderInvoice', cell_style), Paragraph('Customer-facing order invoices', cell_style)],
    [Paragraph('OrderTrackingEvent', cell_style), Paragraph('Shipment tracking timeline', cell_style)],
    [Paragraph('PlatformIntegration', cell_style), Paragraph('External platform integrations (Myntra, Nykaa)', cell_style)],
    [Paragraph('SyncLog', cell_style), Paragraph('Product sync history logs', cell_style)],
    [Paragraph('AffiliateClick', cell_style), Paragraph('Affiliate link click tracking', cell_style)],
    [Paragraph('SupportTicket / Message', cell_style), Paragraph('Customer support ticket system', cell_style)],
    [Paragraph('WikiDocument', cell_style), Paragraph('Internal knowledge base', cell_style)],
    [Paragraph('CurrencyRate', cell_style), Paragraph('Multi-currency exchange rates', cell_style)],
    [Paragraph('GeoCountry', cell_style), Paragraph('Country detection and locale mapping', cell_style)],
]
story.append(make_table(models_admin, [160, AVAILABLE_WIDTH - 160]))

# ═══════════════════════════════════════════════════════════════════
# SECTION 7: API ROUTES REFERENCE
# ═══════════════════════════════════════════════════════════════════
story.append(Spacer(1, 18))
story.append(add_heading('7. API Routes Reference', h1_style, level=0))

story.append(Paragraph(
    'The application exposes 80+ API routes organized into functional groups. All routes are under /api/ '
    'and follow RESTful conventions. Authentication is handled via Bearer token in the Authorization header.',
    body_style
))

story.append(Spacer(1, 8))
story.append(add_heading('7.1 Authentication Routes', h2_style, level=1))
auth_routes = [
    [Paragraph('<b>Route</b>', header_cell_style), Paragraph('<b>Method</b>', header_cell_style), Paragraph('<b>Description</b>', header_cell_style)],
    [Paragraph('/api/auth/register', cell_style), Paragraph('POST', cell_center_style), Paragraph('Register new user', cell_style)],
    [Paragraph('/api/auth/login', cell_style), Paragraph('POST', cell_center_style), Paragraph('Login with email/password', cell_style)],
    [Paragraph('/api/auth/logout', cell_style), Paragraph('POST', cell_center_style), Paragraph('Logout and invalidate session', cell_style)],
    [Paragraph('/api/auth/me', cell_style), Paragraph('GET', cell_center_style), Paragraph('Get current user profile', cell_style)],
    [Paragraph('/api/auth/session', cell_style), Paragraph('GET', cell_center_style), Paragraph('Check session validity', cell_style)],
    [Paragraph('/api/auth/refresh', cell_style), Paragraph('POST', cell_center_style), Paragraph('Refresh auth token', cell_style)],
    [Paragraph('/api/auth/forgot-password', cell_style), Paragraph('POST', cell_center_style), Paragraph('Request password reset', cell_style)],
    [Paragraph('/api/auth/reset-password', cell_style), Paragraph('POST', cell_center_style), Paragraph('Reset password with token', cell_style)],
    [Paragraph('/api/auth/otp/send', cell_style), Paragraph('POST', cell_center_style), Paragraph('Send OTP for phone login', cell_style)],
    [Paragraph('/api/auth/otp/verify', cell_style), Paragraph('POST', cell_center_style), Paragraph('Verify OTP code', cell_style)],
    [Paragraph('/api/auth/2fa/setup', cell_style), Paragraph('POST', cell_center_style), Paragraph('Setup two-factor auth', cell_style)],
    [Paragraph('/api/auth/2fa/verify', cell_style), Paragraph('POST', cell_center_style), Paragraph('Verify 2FA code', cell_style)],
    [Paragraph('/api/auth/social', cell_style), Paragraph('POST', cell_center_style), Paragraph('Social login (Google/Facebook)', cell_style)],
    [Paragraph('/api/auth/approve', cell_style), Paragraph('POST', cell_center_style), Paragraph('Approve user (admin)', cell_style)],
    [Paragraph('/api/auth/verify-email', cell_style), Paragraph('POST', cell_center_style), Paragraph('Verify email address', cell_style)],
    [Paragraph('/api/auth/verify-phone', cell_style), Paragraph('POST', cell_center_style), Paragraph('Verify phone number', cell_style)],
]
story.append(make_table(auth_routes, [170, 50, AVAILABLE_WIDTH - 220]))

story.append(Spacer(1, 8))
story.append(add_heading('7.2 Product and Category Routes', h2_style, level=1))
prod_routes = [
    [Paragraph('<b>Route</b>', header_cell_style), Paragraph('<b>Method</b>', header_cell_style), Paragraph('<b>Description</b>', header_cell_style)],
    [Paragraph('/api/products', cell_style), Paragraph('GET', cell_center_style), Paragraph('List products (supports filtering)', cell_style)],
    [Paragraph('/api/products/[id]', cell_style), Paragraph('GET', cell_center_style), Paragraph('Get single product', cell_style)],
    [Paragraph('/api/categories', cell_style), Paragraph('GET', cell_center_style), Paragraph('List categories', cell_style)],
    [Paragraph('/api/search', cell_style), Paragraph('GET', cell_center_style), Paragraph('Search products by query', cell_style)],
    [Paragraph('/api/gift-recommend', cell_style), Paragraph('GET', cell_center_style), Paragraph('AI-powered gift recommendations', cell_style)],
    [Paragraph('/api/combo-suggestions', cell_style), Paragraph('GET', cell_center_style), Paragraph('Product combo suggestions', cell_style)],
]
story.append(make_table(prod_routes, [170, 50, AVAILABLE_WIDTH - 220]))

story.append(Spacer(1, 8))
story.append(add_heading('7.3 Shopping and Checkout Routes', h2_style, level=1))
cart_routes = [
    [Paragraph('<b>Route</b>', header_cell_style), Paragraph('<b>Method</b>', header_cell_style), Paragraph('<b>Description</b>', header_cell_style)],
    [Paragraph('/api/cart', cell_style), Paragraph('GET/POST', cell_center_style), Paragraph('Get or update cart', cell_style)],
    [Paragraph('/api/checkout', cell_style), Paragraph('POST', cell_center_style), Paragraph('Create checkout session', cell_style)],
    [Paragraph('/api/checkout/estimate', cell_style), Paragraph('POST', cell_center_style), Paragraph('Estimate shipping and tax', cell_style)],
    [Paragraph('/api/orders', cell_style), Paragraph('GET', cell_center_style), Paragraph('List user orders', cell_style)],
    [Paragraph('/api/orders/[id]', cell_style), Paragraph('GET', cell_center_style), Paragraph('Get order details', cell_style)],
    [Paragraph('/api/orders/[id]/tracking', cell_style), Paragraph('GET', cell_center_style), Paragraph('Get order tracking info', cell_style)],
    [Paragraph('/api/orders/[id]/invoice', cell_style), Paragraph('GET', cell_center_style), Paragraph('Download order invoice', cell_style)],
    [Paragraph('/api/orders/[id]/refund', cell_style), Paragraph('POST', cell_center_style), Paragraph('Request order refund', cell_style)],
    [Paragraph('/api/payments/create-session', cell_style), Paragraph('POST', cell_center_style), Paragraph('Create payment session', cell_style)],
    [Paragraph('/api/payments/verify', cell_style), Paragraph('POST', cell_center_style), Paragraph('Verify payment', cell_style)],
    [Paragraph('/api/offers/validate', cell_style), Paragraph('POST', cell_center_style), Paragraph('Validate coupon code', cell_style)],
]
story.append(make_table(cart_routes, [190, 50, AVAILABLE_WIDTH - 240]))

story.append(Spacer(1, 8))
story.append(add_heading('7.4 Admin Routes', h2_style, level=1))
admin_routes = [
    [Paragraph('<b>Route</b>', header_cell_style), Paragraph('<b>Description</b>', header_cell_style)],
    [Paragraph('/api/admin/dashboard', cell_style), Paragraph('Admin dashboard data', cell_style)],
    [Paragraph('/api/admin/stats', cell_style), Paragraph('Platform statistics', cell_style)],
    [Paragraph('/api/admin/users', cell_style), Paragraph('User management (CRUD)', cell_style)],
    [Paragraph('/api/admin/products', cell_style), Paragraph('Product management (CRUD)', cell_style)],
    [Paragraph('/api/admin/categories', cell_style), Paragraph('Category management', cell_style)],
    [Paragraph('/api/admin/orders', cell_style), Paragraph('Order management', cell_style)],
    [Paragraph('/api/admin/corporate', cell_style), Paragraph('Corporate account management', cell_style)],
    [Paragraph('/api/admin/campaigns', cell_style), Paragraph('Campaign management', cell_style)],
    [Paragraph('/api/admin/coupons', cell_style), Paragraph('Coupon management', cell_style)],
    [Paragraph('/api/admin/permissions', cell_style), Paragraph('Permission management', cell_style)],
    [Paragraph('/api/admin/sessions', cell_style), Paragraph('Active session management', cell_style)],
    [Paragraph('/api/admin/audit-logs', cell_style), Paragraph('Audit log viewing', cell_style)],
    [Paragraph('/api/admin/reports', cell_style), Paragraph('Report generation', cell_style)],
    [Paragraph('/api/admin/role-permissions', cell_style), Paragraph('Role-based permissions', cell_style)],
]
story.append(make_table(admin_routes, [190, AVAILABLE_WIDTH - 190]))

story.append(Spacer(1, 8))
story.append(add_heading('7.5 Corporate Gifting Routes', h2_style, level=1))
corp_routes = [
    [Paragraph('<b>Route</b>', header_cell_style), Paragraph('<b>Description</b>', header_cell_style)],
    [Paragraph('/api/corporate/register', cell_style), Paragraph('Register corporate account', cell_style)],
    [Paragraph('/api/corporate/login', cell_style), Paragraph('Corporate login', cell_style)],
    [Paragraph('/api/corporate/profile', cell_style), Paragraph('Corporate profile management', cell_style)],
    [Paragraph('/api/corporate/members', cell_style), Paragraph('Team member management', cell_style)],
    [Paragraph('/api/corporate/branding', cell_style), Paragraph('Branding configuration', cell_style)],
    [Paragraph('/api/corporate/campaigns', cell_style), Paragraph('Campaign CRUD', cell_style)],
    [Paragraph('/api/corporate/campaigns/[id]/recipients', cell_style), Paragraph('Recipient management', cell_style)],
    [Paragraph('/api/corporate/campaigns/[id]/submit', cell_style), Paragraph('Submit campaign for approval', cell_style)],
    [Paragraph('/api/corporate/recipients/import-csv', cell_style), Paragraph('Bulk import recipients via CSV', cell_style)],
]
story.append(make_table(corp_routes, [220, AVAILABLE_WIDTH - 220]))

# ═══════════════════════════════════════════════════════════════════
# SECTION 8: VERCEL CREDENTIALS
# ═══════════════════════════════════════════════════════════════════
story.append(Spacer(1, 18))
story.append(add_heading('8. Complete Credentials Reference', h1_style, level=0))

story.append(Paragraph(
    'This section contains all credentials and access details for the deployed application. '
    'Keep this document secure as it contains sensitive API keys and tokens.',
    body_style
))

story.append(Spacer(1, 8))
story.append(add_heading('8.1 Vercel Deployment', h2_style, level=1))
vercel_creds = [
    [Paragraph('<b>Property</b>', header_cell_style), Paragraph('<b>Value</b>', header_cell_style)],
    [Paragraph('Project URL', cell_style), Paragraph('https://my-project-sepia-seven-42.vercel.app', cell_style)],
    [Paragraph('Vercel Dashboard', cell_style), Paragraph('https://vercel.com/dashboard', cell_style)],
    [Paragraph('Vercel Token', cell_style), Paragraph('vcp_2mJFo9UaGarHsCeVd8wRTiwWevFJaulJdtaC9PpKwqsa1YUMZV2Dzipr', cell_style)],
    [Paragraph('Region', cell_style), Paragraph('bom1 (Mumbai, India)', cell_style)],
    [Paragraph('Framework', cell_style), Paragraph('Next.js', cell_style)],
    [Paragraph('Build Command', cell_style), Paragraph('Custom (see vercel.json)', cell_style)],
    [Paragraph('Install Command', cell_style), Paragraph('bun install', cell_style)],
]
story.append(make_table(vercel_creds, [140, AVAILABLE_WIDTH - 140]))

story.append(Spacer(1, 8))
story.append(add_heading('8.2 Shopify Store', h2_style, level=1))
shopify_creds = [
    [Paragraph('<b>Property</b>', header_cell_style), Paragraph('<b>Value</b>', header_cell_style)],
    [Paragraph('Store Domain', cell_style), Paragraph('3boxesluxury-2.myshopify.com', cell_style)],
    [Paragraph('Admin URL', cell_style), Paragraph('https://3boxesluxury-2.myshopify.com/admin', cell_style)],
    [Paragraph('Admin API Token', cell_style), Paragraph('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', cell_style)],
    [Paragraph('Storefront API Token', cell_style), Paragraph('09124abbd07ca423DB9488B3DC2C737F', cell_style)],
    [Paragraph('API Version', cell_style), Paragraph('2024-10', cell_style)],
]
story.append(make_table(shopify_creds, [160, AVAILABLE_WIDTH - 160]))

story.append(Spacer(1, 8))
story.append(add_heading('8.3 Database', h2_style, level=1))
db_creds = [
    [Paragraph('<b>Property</b>', header_cell_style), Paragraph('<b>Value</b>', header_cell_style)],
    [Paragraph('Provider (Production)', cell_style), Paragraph('PostgreSQL (Neon Serverless)', cell_style)],
    [Paragraph('Provider (Development)', cell_style), Paragraph('SQLite (local file)', cell_style)],
    [Paragraph('DATABASE_URL (Current)', cell_style), Paragraph('postgresql://user:pass@ep-xxx.neon.tech/dbname?sslmode=require', cell_style)],
    [Paragraph('DATABASE_URL (Required)', cell_style), Paragraph('Real Neon connection string (needs update)', cell_style)],
    [Paragraph('Local DB Path', cell_style), Paragraph('file:/home/z/my-project/db/custom.db', cell_style)],
    [Paragraph('Prisma Schema', cell_style), Paragraph('prisma/schema.prisma', cell_style)],
    [Paragraph('ORM', cell_style), Paragraph('Prisma Client v6.11.1', cell_style)],
]
story.append(make_table(db_creds, [160, AVAILABLE_WIDTH - 160]))
story.append(note('The DATABASE_URL on Vercel currently points to a placeholder. It MUST be updated with a real Neon PostgreSQL connection string for full functionality.'))

# ═══════════════════════════════════════════════════════════════════
# SECTION 9: TROUBLESHOOTING
# ═══════════════════════════════════════════════════════════════════
story.append(Spacer(1, 18))
story.append(add_heading('9. Troubleshooting Guide', h1_style, level=0))

story.append(add_heading('9.1 Build Failures', h2_style, level=1))
story.append(Paragraph('<b>Problem: Prisma db push fails on Vercel</b>', h3_style))
story.append(bullet('Cause: DATABASE_URL is a placeholder or invalid connection string'))
story.append(bullet('Fix: Update DATABASE_URL with a valid Neon PostgreSQL connection string'))
story.append(bullet('Verify: Test the connection string locally with: npx prisma db push'))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>Problem: TypeScript build errors</b>', h3_style))
story.append(bullet('The project uses ignoreBuildErrors: true in next.config.ts to bypass TS errors'))
story.append(bullet('This is intentional for rapid deployment; fix TS errors locally before production'))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>Problem: SQLite to PostgreSQL switch fails</b>', h3_style))
story.append(bullet('The vercel-build script uses sed to switch the Prisma provider'))
story.append(bullet('If this fails, verify that prisma/schema.prisma has: provider = "sqlite"'))
story.append(bullet('The sed command replaces "sqlite" with "postgresql" during build'))

story.append(Spacer(1, 8))
story.append(add_heading('9.2 Runtime Errors', h2_style, level=1))
story.append(Paragraph('<b>Problem: Cart/Orders/Admin pages return 500 errors</b>', h3_style))
story.append(bullet('Cause: Database connection fails (placeholder DATABASE_URL)'))
story.append(bullet('Fix: Update DATABASE_URL with real Neon connection string'))
story.append(bullet('Products/Categories still work via Shopify Admin API fallback'))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>Problem: Shopify API returns 401 Unauthorized</b>', h3_style))
story.append(bullet('Cause: Invalid or expired API token'))
story.append(bullet('Fix: Regenerate the token in Shopify Admin > Apps > Develop apps'))

story.append(Spacer(1, 6))
story.append(Paragraph('<b>Problem: Vercel Deployment Protection blocks access</b>', h3_style))
story.append(bullet('Cause: Vercel Standard/Pro plans have Deployment Protection enabled by default'))
story.append(bullet('Fix: Go to Vercel Dashboard > Settings > Deployment Protection > Disable'))

story.append(Spacer(1, 8))
story.append(add_heading('9.3 Quick Diagnostic Commands', h2_style, level=1))
story.append(code_block('# Check Vercel deployment status'))
story.append(code_block('vercel ls'))
story.append(code_block(''))
story.append(code_block('# View deployment logs'))
story.append(code_block('vercel logs https://my-project-sepia-seven-42.vercel.app'))
story.append(code_block(''))
story.append(code_block('# Check environment variables'))
story.append(code_block('vercel env ls'))
story.append(code_block(''))
story.append(code_block('# Test Shopify API connection'))
story.append(code_block('curl -H "X-Shopify-Access-Token: shpat_..." \\'))
story.append(code_block('  "https://3boxesluxury-2.myshopify.com/admin/api/2024-10/products/count.json"'))
story.append(code_block(''))
story.append(code_block('# Test database connection locally'))
story.append(code_block('npx prisma db push --schema=prisma/schema.prisma'))
story.append(code_block(''))
story.append(code_block('# Redeploy to production'))
story.append(code_block('vercel --prod'))

# ═══════════════════════════════════════════════════════════════════
# SECTION 10: COMPLETE SETUP CHECKLIST
# ═══════════════════════════════════════════════════════════════════
story.append(Spacer(1, 18))
story.append(add_heading('10. Complete Setup Checklist', h1_style, level=0))

story.append(Paragraph(
    'Follow this checklist to get the 3 BOXES LUXURY application fully operational on Vercel:',
    body_style
))

checklist_data = [
    [Paragraph('<b>#</b>', header_cell_style), Paragraph('<b>Task</b>', header_cell_style), Paragraph('<b>Status</b>', header_cell_style), Paragraph('<b>Details</b>', header_cell_style)],
    [Paragraph('1', cell_center_style), Paragraph('Create Neon PostgreSQL database', cell_style), Paragraph('PENDING', cell_style), Paragraph('Go to console.neon.tech, create free project', cell_style)],
    [Paragraph('2', cell_center_style), Paragraph('Copy Neon connection string', cell_style), Paragraph('PENDING', cell_style), Paragraph('From Neon dashboard, copy the postgresql://... URL', cell_style)],
    [Paragraph('3', cell_center_style), Paragraph('Update DATABASE_URL on Vercel', cell_style), Paragraph('PENDING', cell_style), Paragraph('Settings > Environment Variables > Edit DATABASE_URL', cell_style)],
    [Paragraph('4', cell_center_style), Paragraph('Set SHOPIFY_STORE_DOMAIN', cell_style), Paragraph('DONE', cell_style), Paragraph('3boxesluxury-2.myshopify.com', cell_style)],
    [Paragraph('5', cell_center_style), Paragraph('Set SHOPIFY_ADMIN_API_TOKEN', cell_style), Paragraph('DONE', cell_style), Paragraph('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', cell_style)],
    [Paragraph('6', cell_center_style), Paragraph('Set SHOPIFY_STOREFRONT_ACCESS_TOKEN', cell_style), Paragraph('DONE', cell_style), Paragraph('09124abbd07ca423DB9488B3DC2C737F', cell_style)],
    [Paragraph('7', cell_center_style), Paragraph('Set NEXTAUTH_SECRET', cell_style), Paragraph('PENDING', cell_style), Paragraph('Generate: openssl rand -base64 32', cell_style)],
    [Paragraph('8', cell_center_style), Paragraph('Set NEXTAUTH_URL', cell_style), Paragraph('PENDING', cell_style), Paragraph('https://my-project-sepia-seven-42.vercel.app', cell_style)],
    [Paragraph('9', cell_center_style), Paragraph('Disable Deployment Protection', cell_style), Paragraph('PENDING', cell_style), Paragraph('Vercel > Settings > Deployment Protection', cell_style)],
    [Paragraph('10', cell_center_style), Paragraph('Redeploy to production', cell_style), Paragraph('PENDING', cell_style), Paragraph('Run: vercel --prod', cell_style)],
    [Paragraph('11', cell_center_style), Paragraph('Verify products load', cell_style), Paragraph('DONE', cell_style), Paragraph('Products work via Shopify fallback', cell_style)],
    [Paragraph('12', cell_center_style), Paragraph('Verify cart/checkout works', cell_style), Paragraph('PENDING', cell_style), Paragraph('Needs real DATABASE_URL', cell_style)],
    [Paragraph('13', cell_center_style), Paragraph('Verify user registration', cell_style), Paragraph('PENDING', cell_style), Paragraph('Needs real DATABASE_URL', cell_style)],
    [Paragraph('14', cell_center_style), Paragraph('Verify admin dashboard', cell_style), Paragraph('PENDING', cell_style), Paragraph('Needs real DATABASE_URL', cell_style)],
    [Paragraph('15', cell_center_style), Paragraph('Verify corporate gifting', cell_style), Paragraph('PENDING', cell_style), Paragraph('Needs real DATABASE_URL', cell_style)],
]
story.append(make_table(checklist_data, [25, 170, 60, AVAILABLE_WIDTH - 255]))

story.append(Spacer(1, 18))
story.append(hr())
story.append(Paragraph(
    '<b>End of Document</b> - For questions or support, refer to the Vercel documentation at '
    'https://vercel.com/docs and the Neon documentation at https://neon.tech/docs.',
    ParagraphStyle('Footer', fontName='LibSerif', fontSize=10, leading=14,
                   textColor=TEXT_MUTED, alignment=TA_CENTER)
))

# ─── Build the PDF ───
doc.multiBuild(story)
print(f"PDF generated successfully: {output_path}")
