import { db } from "@/lib/db";

const categories = [
  {
    name: "Watches",
    slug: "watches",
    description: "Luxury timepieces from world-renowned makers",
    image: "/images/categories/watches.jpg",
  },
  {
    name: "Jewelry",
    slug: "jewelry",
    description: "Exquisite jewelry crafted with precious stones and metals",
    image: "/images/categories/jewelry.jpg",
  },
  {
    name: "Leather Goods",
    slug: "leather-goods",
    description: "Premium leather bags, wallets, and accessories",
    image: "/images/categories/leather.jpg",
  },
  {
    name: "Fragrances",
    slug: "fragrances",
    description: "Signature scents from the world's finest perfumers",
    image: "/images/categories/fragrances.jpg",
  },
  {
    name: "Fashion",
    slug: "fashion",
    description: "Designer clothing and haute couture collections",
    image: "/images/categories/fashion.jpg",
  },
  {
    name: "Home & Living",
    slug: "home-living",
    description: "Luxurious home décor and lifestyle accessories",
    image: "/images/categories/home.jpg",
  },
  {
    name: "Sarees",
    slug: "sarees",
    description: "Handwoven silk and designer sarees for every occasion",
    image: "/images/categories/sarees.jpg",
  },
  {
    name: "Toys",
    slug: "toys",
    description: "Premium collectible toys and luxury gifts for all ages",
    image: "/images/categories/toys.jpg",
  },
  {
    name: "Romantic Gifts",
    slug: "romantic-gifts",
    description: "Thoughtful gift experiences to express your love",
    image: "/images/categories/romantic.jpg",
  },
  {
    name: "Couple Friendly Gifts",
    slug: "couple-gifts",
    description: "Gift experiences for couples to share together",
    image: "/images/categories/couple.jpg",
  },
  {
    name: "Men's Shirts & T-Shirts",
    slug: "mens-shirts",
    description: "Premium shirts and t-shirts for the modern gentleman",
    image: "/images/categories/mens-shirts.jpg",
  },
];

const products = [
  // Watches
  {
    name: "Royal Chronograph Gold",
    slug: "royal-chronograph-gold",
    description: "An exquisite 18K gold chronograph with Swiss movement, sapphire crystal, and alligator leather strap. Water-resistant to 100 meters with moon phase complication.",
    price: 12500,
    compareAtPrice: 15000,
    images: JSON.stringify(["/images/products/watch-1.jpg", "/images/products/watch-1-alt.jpg"]),
    categorySlug: "watches",
    stock: 5,
    rating: 4.9,
    reviewCount: 47,
    featured: true,
    tags: JSON.stringify(["gold", "chronograph", "swiss", "luxury"]),
  },
  {
    name: "Midnight Tourbillon",
    slug: "midnight-tourbillon",
    description: "A masterpiece of horological engineering featuring a flying tourbillon, midnight blue dial, and platinum case. Limited edition of 50 pieces worldwide.",
    price: 45000,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/watch-2.jpg", "/images/products/watch-2-alt.jpg"]),
    categorySlug: "watches",
    stock: 2,
    rating: 5.0,
    reviewCount: 12,
    featured: true,
    tags: JSON.stringify(["tourbillon", "platinum", "limited", "swiss"]),
  },
  {
    name: "Classic Automatic Silver",
    slug: "classic-automatic-silver",
    description: "Timeless elegance with automatic movement, silver dial, and stainless steel bracelet. A perfect everyday luxury timepiece.",
    price: 4200,
    compareAtPrice: 5000,
    images: JSON.stringify(["/images/products/watch-3.jpg"]),
    categorySlug: "watches",
    stock: 15,
    rating: 4.7,
    reviewCount: 89,
    featured: false,
    tags: JSON.stringify(["automatic", "silver", "classic"]),
  },
  {
    name: "Diamond Bezel Diver",
    slug: "diamond-bezel-diver",
    description: "A stunning dive watch with diamond-set bezel, ceramic insert, and 300m water resistance. Where adventure meets luxury.",
    price: 18500,
    compareAtPrice: 22000,
    images: JSON.stringify(["/images/products/watch-4.jpg"]),
    categorySlug: "watches",
    stock: 8,
    rating: 4.8,
    reviewCount: 34,
    featured: true,
    tags: JSON.stringify(["diamond", "diver", "ceramic"]),
  },

  // Jewelry
  {
    name: "Eternal Diamond Necklace",
    slug: "eternal-diamond-necklace",
    description: "A breathtaking 5-carat diamond pendant on an 18K white gold chain. GIA certified, VS1 clarity, D color.",
    price: 28000,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/jewelry-1.jpg", "/images/products/jewelry-1-alt.jpg"]),
    categorySlug: "jewelry",
    stock: 3,
    rating: 5.0,
    reviewCount: 22,
    featured: true,
    tags: JSON.stringify(["diamond", "necklace", "white-gold"]),
  },
  {
    name: "Ruby Empire Ring",
    slug: "ruby-empire-ring",
    description: "A magnificent 3-carat Burmese ruby surrounded by diamonds, set in 18K rose gold. A statement piece of extraordinary beauty.",
    price: 35000,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/jewelry-2.jpg"]),
    categorySlug: "jewelry",
    stock: 2,
    rating: 4.9,
    reviewCount: 15,
    featured: true,
    tags: JSON.stringify(["ruby", "ring", "rose-gold"]),
  },
  {
    name: "Sapphire Cascade Earrings",
    slug: "sapphire-cascade-earrings",
    description: "Elegant cascade earrings featuring Ceylon sapphires and diamonds in platinum setting. Total gemstone weight 4.5 carats.",
    price: 8900,
    compareAtPrice: 10500,
    images: JSON.stringify(["/images/products/jewelry-3.jpg"]),
    categorySlug: "jewelry",
    stock: 6,
    rating: 4.8,
    reviewCount: 31,
    featured: false,
    tags: JSON.stringify(["sapphire", "earrings", "platinum"]),
  },
  {
    name: "Emerald Tennis Bracelet",
    slug: "emerald-tennis-bracelet",
    description: "A stunning tennis bracelet featuring 5 carats of graduated Colombian emeralds, each surrounded by a halo of brilliant-cut diamonds in 18K white gold. The flexible setting ensures comfort and elegance on the wrist.",
    price: 15800,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/jewelry-4.jpg"]),
    categorySlug: "jewelry",
    stock: 4,
    rating: 4.9,
    reviewCount: 19,
    featured: true,
    tags: JSON.stringify(["emerald", "bracelet", "white-gold", "diamond-halo"]),
  },
  {
    name: "South Sea Pearl Choker",
    slug: "south-sea-pearl-choker",
    description: "A magnificent choker of hand-selected South Sea pearls, each 12-13mm with exceptional luster and overtone. Fastened with a diamond-paved platinum clasp. A timeless statement of refined elegance.",
    price: 12500,
    compareAtPrice: 14000,
    images: JSON.stringify(["/images/products/jewelry-5.jpg"]),
    categorySlug: "jewelry",
    stock: 5,
    rating: 4.8,
    reviewCount: 24,
    featured: true,
    tags: JSON.stringify(["pearl", "choker", "south-sea", "platinum", "diamond-clasp"]),
  },
  {
    name: "Brilliant Diamond Stud Earrings",
    slug: "brilliant-diamond-stud-earrings",
    description: "Classic diamond stud earrings featuring 2-carat each round brilliant-cut diamonds (GIA certified, F color, VS1 clarity) in platinum four-prong martini settings. The essential luxury staple.",
    price: 18500,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/jewelry-6.jpg"]),
    categorySlug: "jewelry",
    stock: 6,
    rating: 5.0,
    reviewCount: 41,
    featured: true,
    tags: JSON.stringify(["diamond", "studs", "platinum", "GIA", "brilliant-cut"]),
  },
  {
    name: "Kundan Bridal Jewelry Set",
    slug: "kundan-bridal-jewelry-set",
    description: "A breathtaking Kundan bridal set featuring a grand necklace and matching jhumka earrings. Uncut Polki diamonds, Colombian emeralds, and Burmese rubies set in 22K gold using traditional Rajasthani techniques. A bride's dream.",
    price: 22000,
    compareAtPrice: 25000,
    images: JSON.stringify(["/images/products/jewelry-7.jpg"]),
    categorySlug: "jewelry",
    stock: 2,
    rating: 5.0,
    reviewCount: 16,
    featured: true,
    tags: JSON.stringify(["kundan", "bridal", "polki", "uncut-diamond", "emerald", "ruby", "22K-gold"]),
  },
  {
    name: "Temple Gold Lakshmi Necklace",
    slug: "temple-gold-lakshmi-necklace",
    description: "A traditional South Indian temple necklace in 22K gold featuring intricately carved Goddess Lakshmi coins with ruby and emerald accents. The coin fringe design is a timeless symbol of prosperity and devotion.",
    price: 9800,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/jewelry-8.jpg"]),
    categorySlug: "jewelry",
    stock: 4,
    rating: 4.9,
    reviewCount: 28,
    featured: true,
    tags: JSON.stringify(["temple", "22K-gold", "lakshmi", "south-indian", "ruby", "coin-necklace"]),
  },
  {
    name: "Polki Diamond Jhumka Earrings",
    slug: "polki-diamond-jhumka-earrings",
    description: "Exquisite Polki diamond jhumka earrings featuring uncut diamonds and seed pearls in a traditional bell-shaped design. The gold setting is hand-finished with meenakari enamel work on the reverse. A perfect blend of heritage and luxury.",
    price: 4500,
    compareAtPrice: 5200,
    images: JSON.stringify(["/images/products/jewelry-9.jpg"]),
    categorySlug: "jewelry",
    stock: 8,
    rating: 4.8,
    reviewCount: 52,
    featured: true,
    tags: JSON.stringify(["polki", "jhumka", "uncut-diamond", "meenakari", "pearl", "traditional"]),
  },
  {
    name: "Antique Silver Turquoise Cuff",
    slug: "antique-silver-turquoise-cuff",
    description: "A bold oxidized silver cuff bracelet featuring Sleeping Beauty turquoise cabochons set in intricate filigree work. The bohemian-luxury design draws inspiration from Rajasthani tribal jewelry. Adjustable fit.",
    price: 1200,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/jewelry-10.jpg"]),
    categorySlug: "jewelry",
    stock: 10,
    rating: 4.6,
    reviewCount: 37,
    featured: false,
    tags: JSON.stringify(["silver", "cuff", "turquoise", "filigree", "boho", "oxidized"]),
  },

  // Leather Goods
  {
    name: "Heritage Leather Briefcase",
    slug: "heritage-leather-briefcase",
    description: "Handcrafted Italian calfskin leather briefcase with brass hardware. Features laptop compartment, organizer pockets, and detachable shoulder strap.",
    price: 1850,
    compareAtPrice: 2200,
    images: JSON.stringify(["/images/products/leather-1.jpg", "/images/products/leather-1-alt.jpg"]),
    categorySlug: "leather-goods",
    stock: 12,
    rating: 4.8,
    reviewCount: 67,
    featured: true,
    tags: JSON.stringify(["briefcase", "italian-leather", "calfskin"]),
  },
  {
    name: "Monogram Travel Trunk",
    slug: "monogram-travel-trunk",
    description: "A legendary monogram canvas trunk with natural cowhide trim. The epitome of luxury travel, handcrafted with over 150 years of heritage.",
    price: 5200,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/leather-2.jpg"]),
    categorySlug: "leather-goods",
    stock: 4,
    rating: 4.9,
    reviewCount: 28,
    featured: true,
    tags: JSON.stringify(["trunk", "monogram", "travel"]),
  },
  {
    name: "Bifold Wallet in Epi Leather",
    slug: "bifold-wallet-epi",
    description: "Slim bifold wallet in textured Epi leather with multiple card slots and bill compartment. A refined essential.",
    price: 650,
    compareAtPrice: 780,
    images: JSON.stringify(["/images/products/leather-3.jpg"]),
    categorySlug: "leather-goods",
    stock: 25,
    rating: 4.6,
    reviewCount: 112,
    featured: false,
    tags: JSON.stringify(["wallet", "epi-leather", "slim"]),
  },

  // Fragrances
  {
    name: "Noir Absolu Parfum",
    slug: "noir-absolu-parfum",
    description: "An intoxicating blend of black amber, oud wood, and Bulgarian rose. A bold, sophisticated fragrance for the discerning connoisseur.",
    price: 420,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/fragrance-1.jpg", "/images/products/fragrance-1-alt.jpg"]),
    categorySlug: "fragrances",
    stock: 30,
    rating: 4.8,
    reviewCount: 156,
    featured: true,
    tags: JSON.stringify(["oud", "amber", "unisex"]),
  },
  {
    name: "Jardin Secret Eau de Parfum",
    slug: "jardin-secret-edp",
    description: "A secret garden captured in a bottle — jasmine sambac, tuberose, and fresh fig leaf create an enchanting feminine fragrance.",
    price: 350,
    compareAtPrice: 420,
    images: JSON.stringify(["/images/products/fragrance-2.jpg"]),
    categorySlug: "fragrances",
    stock: 40,
    rating: 4.7,
    reviewCount: 203,
    featured: false,
    tags: JSON.stringify(["floral", "jasmine", "feminine"]),
  },
  {
    name: "Vetiver Imperial Cologne",
    slug: "vetiver-imperial-cologne",
    description: "A refined masculine cologne featuring Haitian vetiver, Italian bergamot, and pepper. Timeless sophistication in every spritz.",
    price: 280,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/fragrance-3.jpg"]),
    categorySlug: "fragrances",
    stock: 50,
    rating: 4.6,
    reviewCount: 178,
    featured: false,
    tags: JSON.stringify(["vetiver", "bergamot", "masculine"]),
  },

  // Fashion
  {
    name: "Cashmere Overcoat",
    slug: "cashmere-overcoat",
    description: "Double-breasted overcoat in pure Italian cashmere. Tailored silhouette with satin lining, horn buttons, and hand-finished details.",
    price: 3200,
    compareAtPrice: 3800,
    images: JSON.stringify(["/images/products/fashion-1.jpg", "/images/products/fashion-1-alt.jpg"]),
    categorySlug: "fashion",
    stock: 8,
    rating: 4.9,
    reviewCount: 43,
    featured: true,
    tags: JSON.stringify(["cashmere", "overcoat", "italian"]),
  },
  {
    name: "Silk Evening Gown",
    slug: "silk-evening-gown",
    description: "A stunning floor-length gown in pure silk charmeuse with delicate crystal embellishments. Designed for the most memorable occasions.",
    price: 5800,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/fashion-2.jpg"]),
    categorySlug: "fashion",
    stock: 4,
    rating: 5.0,
    reviewCount: 19,
    featured: true,
    tags: JSON.stringify(["silk", "gown", "crystal"]),
  },
  {
    name: "Tailored Linen Blazer",
    slug: "tailored-linen-blazer",
    description: "Impeccably tailored linen blazer with half-canvas construction. Perfect for warm-weather sophistication.",
    price: 1450,
    compareAtPrice: 1700,
    images: JSON.stringify(["/images/products/fashion-3.jpg"]),
    categorySlug: "fashion",
    stock: 10,
    rating: 4.7,
    reviewCount: 55,
    featured: false,
    tags: JSON.stringify(["linen", "blazer", "tailored"]),
  },

  // Home & Living
  {
    name: "Murano Crystal Vase",
    slug: "murano-crystal-vase",
    description: "Handblown Murano crystal vase with 24K gold leaf inclusions. Each piece is a unique work of art, signed by the master glassblower.",
    price: 2800,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/home-1.jpg", "/images/products/home-1-alt.jpg"]),
    categorySlug: "home-living",
    stock: 7,
    rating: 4.8,
    reviewCount: 24,
    featured: true,
    tags: JSON.stringify(["murano", "crystal", "vase", "gold-leaf"]),
  },
  {
    name: "Silk Throw Pillow Set",
    slug: "silk-throw-pillow-set",
    description: "Set of 4 hand-embroidered silk throw pillows with gold thread accents. Filled with premium duck down for luxurious comfort.",
    price: 950,
    compareAtPrice: 1200,
    images: JSON.stringify(["/images/products/home-2.jpg"]),
    categorySlug: "home-living",
    stock: 15,
    rating: 4.6,
    reviewCount: 41,
    featured: false,
    tags: JSON.stringify(["silk", "pillow", "embroidered"]),
  },
  {
    name: "Artisan Scented Candle Collection",
    slug: "artisan-scented-candles",
    description: "A collection of 6 artisan candles hand-poured in amber glass vessels. Notes of sandalwood, vanilla, and exotic spices. Total burn time: 240 hours.",
    price: 380,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/home-3.jpg"]),
    categorySlug: "home-living",
    stock: 20,
    rating: 4.5,
    reviewCount: 87,
    featured: false,
    tags: JSON.stringify(["candles", "scented", "artisan"]),
  },

  // Sarees
  {
    name: "Banarasi Silk Saree",
    slug: "banarasi-silk-saree",
    description: "A magnificent Banarasi silk saree with intricate gold zari work. Handwoven by master craftsmen, this heirloom piece features traditional Mughal motifs and a rich pallu. Perfect for weddings and grand celebrations.",
    price: 1850,
    compareAtPrice: 2200,
    images: JSON.stringify(["/images/products/saree-1.jpg"]),
    categorySlug: "sarees",
    stock: 8,
    rating: 4.9,
    reviewCount: 56,
    featured: true,
    tags: JSON.stringify(["silk", "banarasi", "zari", "wedding", "handwoven"]),
  },
  {
    name: "Kanjeevaram Silk Saree",
    slug: "kanjeevaram-silk-saree",
    description: "A stunning Kanjeevaram silk saree in vibrant magenta with contrasting golden border. Woven with pure mulberry silk and real gold threads, this saree is a South Indian treasure.",
    price: 2400,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/saree-2.jpg"]),
    categorySlug: "sarees",
    stock: 5,
    rating: 5.0,
    reviewCount: 34,
    featured: true,
    tags: JSON.stringify(["silk", "kanjeevaram", "gold-thread", "temple-border"]),
  },
  {
    name: "Designer Chiffon Saree",
    slug: "designer-chiffon-saree",
    description: "An elegant designer chiffon saree with delicate embroidery and sequin work. Lightweight and flowing, perfect for parties and festive occasions. Includes matching blouse piece.",
    price: 780,
    compareAtPrice: 950,
    images: JSON.stringify(["/images/products/saree-3.jpg"]),
    categorySlug: "sarees",
    stock: 15,
    rating: 4.7,
    reviewCount: 89,
    featured: false,
    tags: JSON.stringify(["chiffon", "embroidered", "sequin", "party-wear"]),
  },
  {
    name: "Patola Double Ikat Saree",
    slug: "patola-double-ikat-saree",
    description: "A rare Patola silk saree from Patan, featuring the ancient double ikat technique where both warp and weft threads are tie-dyed before weaving. Royal blue and red geometric patterns create a mesmerizing visual. A true collector's piece.",
    price: 3200,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/saree-4.jpg"]),
    categorySlug: "sarees",
    stock: 4,
    rating: 5.0,
    reviewCount: 18,
    featured: true,
    tags: JSON.stringify(["patola", "double-ikat", "handwoven", "heritage", "collector"]),
  },
  {
    name: "Organza Floral Dream Saree",
    slug: "organza-floral-dream-saree",
    description: "A breathtaking organza saree in blush pink with exquisite 3D floral appliqué work. Delicate pastel flowers cascade across the drape, creating a fairy-tale aesthetic. Includes pre-stitched pleats and matching blouse.",
    price: 1650,
    compareAtPrice: 1900,
    images: JSON.stringify(["/images/products/saree-5.jpg"]),
    categorySlug: "sarees",
    stock: 7,
    rating: 4.8,
    reviewCount: 42,
    featured: true,
    tags: JSON.stringify(["organza", "floral", "3D-applique", "contemporary", "reception"]),
  },
  {
    name: "Tussar Silk Tribal Art Saree",
    slug: "tussar-silk-tribal-art-saree",
    description: "A hand-painted Tussar silk saree in natural golden-beige tone featuring traditional tribal motifs from Jharkhand. The raw silk texture and earthy elegance make this a sustainable luxury choice. Each piece is unique.",
    price: 1100,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/saree-6.jpg"]),
    categorySlug: "sarees",
    stock: 10,
    rating: 4.6,
    reviewCount: 35,
    featured: false,
    tags: JSON.stringify(["tussar", "hand-painted", "tribal", "sustainable", "eco-friendly"]),
  },
  {
    name: "Velvet Zardozi Bridal Saree",
    slug: "velvet-zardozi-bridal-saree",
    description: "An opulent deep maroon velvet bridal saree with intricate zardozi embroidery using real gold and silver threads. Features heavy embellished borders and pallu with Mughal-inspired floral patterns. The ultimate wedding statement piece.",
    price: 4800,
    compareAtPrice: 5500,
    images: JSON.stringify(["/images/products/saree-7.jpg"]),
    categorySlug: "sarees",
    stock: 3,
    rating: 5.0,
    reviewCount: 27,
    featured: true,
    tags: JSON.stringify(["velvet", "zardozi", "bridal", "gold-thread", "wedding", "mughal"]),
  },
  {
    name: "Chanderi Mint Elegance Saree",
    slug: "chanderi-mint-elegance-saree",
    description: "A feather-light Chanderi cotton-silk saree in refreshing mint green with delicate gold butis scattered across the drape. The sheer fabric creates a graceful silhouette perfect for daytime events and pujas.",
    price: 680,
    compareAtPrice: 820,
    images: JSON.stringify(["/images/products/saree-8.jpg"]),
    categorySlug: "sarees",
    stock: 12,
    rating: 4.5,
    reviewCount: 63,
    featured: false,
    tags: JSON.stringify(["chanderi", "cotton-silk", "lightweight", "day-wear", "traditional"]),
  },
  {
    name: "Paithani Peacock Heritage Saree",
    slug: "paithani-peacock-heritage-saree",
    description: "A magnificent Paithani silk saree in rich purple with the iconic peacock motif pallu woven in gold zari. Handloomed in Yeola, Maharashtra, this heritage piece features the distinctive oblique weave that creates a distinctive texture.",
    price: 3600,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/saree-9.jpg"]),
    categorySlug: "sarees",
    stock: 5,
    rating: 4.9,
    reviewCount: 22,
    featured: true,
    tags: JSON.stringify(["paithani", "peacock", "handloom", "maharashtra", "heritage", "zari"]),
  },
  {
    name: "Georgette Crystal Glam Saree",
    slug: "georgette-crystal-glam-saree",
    description: "A show-stopping georgette saree in champagne gold adorned with Swarovski crystals and stone work. The lightweight fabric drapes beautifully while the sparkling embellishments catch every light. Perfect for cocktail parties and receptions.",
    price: 2100,
    compareAtPrice: 2500,
    images: JSON.stringify(["/images/products/saree-10.jpg"]),
    categorySlug: "sarees",
    stock: 6,
    rating: 4.8,
    reviewCount: 38,
    featured: true,
    tags: JSON.stringify(["georgette", "crystal", "swarovski", "cocktail", "party-wear", "glam"]),
  },

  // Toys
  {
    name: "Luxury Crystal Chess Set",
    slug: "luxury-crystal-chess-set",
    description: "A breathtaking chess set with hand-carved crystal pieces on a rosewood and maple board. Each piece is a miniature sculpture, making this a collector's dream and a stunning display piece.",
    price: 1200,
    compareAtPrice: 1500,
    images: JSON.stringify(["/images/products/toy-1.jpg"]),
    categorySlug: "toys",
    stock: 6,
    rating: 4.8,
    reviewCount: 28,
    featured: true,
    tags: JSON.stringify(["crystal", "chess", "collector", "rosewood"]),
  },
  {
    name: "Limited Edition Model Car",
    slug: "limited-edition-model-car",
    description: "A 1:8 scale die-cast model of a classic Ferrari 250 GTO. Hand-assembled with over 1,500 parts, opening doors, hood, and detailed engine bay. Limited to 999 pieces worldwide.",
    price: 3500,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/toy-2.jpg"]),
    categorySlug: "toys",
    stock: 3,
    rating: 5.0,
    reviewCount: 15,
    featured: true,
    tags: JSON.stringify(["ferrari", "die-cast", "limited-edition", "collectible"]),
  },
  {
    name: "Premium Wooden Train Set",
    slug: "premium-wooden-train-set",
    description: "An heirloom-quality wooden train set handcrafted from sustainable beech wood. Includes 52 pieces with magnetic connectors, bridges, and stations. Non-toxic paints, safe for all ages.",
    price: 450,
    compareAtPrice: 580,
    images: JSON.stringify(["/images/products/toy-3.jpg"]),
    categorySlug: "toys",
    stock: 12,
    rating: 4.7,
    reviewCount: 67,
    featured: false,
    tags: JSON.stringify(["wooden", "train", "handcrafted", "sustainable"]),
  },

  // Romantic Gifts
  {
    name: "Enchanted Rose Box",
    slug: "enchanted-rose-box",
    description: "A preserved eternal rose under a glass dome, inspired by fairy tales. Available in red, pink, or white. Comes in a premium gift box with a handwritten card. A timeless symbol of love.",
    price: 320,
    compareAtPrice: 400,
    images: JSON.stringify(["/images/products/romantic-1.jpg"]),
    categorySlug: "romantic-gifts",
    stock: 20,
    rating: 4.8,
    reviewCount: 142,
    featured: true,
    tags: JSON.stringify(["rose", "eternal", "glass-dome", "love"]),
  },
  {
    name: "Couple's Star Map Print",
    slug: "couples-star-map",
    description: "A custom star map showing the exact alignment of stars and constellations at a specific date and location. Perfect for commemorating anniversaries, first meetings, or special moments. Museum-quality archival print.",
    price: 180,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/romantic-2.jpg"]),
    categorySlug: "romantic-gifts",
    stock: 30,
    rating: 4.9,
    reviewCount: 89,
    featured: true,
    tags: JSON.stringify(["star-map", "custom", "anniversary", "print"]),
  },
  {
    name: "Luxury Date Night Hamper",
    slug: "luxury-date-night-hamper",
    description: "A curated hamper for the perfect date night at home. Includes artisan chocolates, premium wine glasses, scented candles, a silk blindfold, and a couples activity book. Elegantly packaged.",
    price: 550,
    compareAtPrice: 680,
    images: JSON.stringify(["/images/products/romantic-3.jpg"]),
    categorySlug: "romantic-gifts",
    stock: 10,
    rating: 4.7,
    reviewCount: 56,
    featured: false,
    tags: JSON.stringify(["hamper", "date-night", "chocolate", "candles"]),
  },

  // Couple Friendly Gifts
  {
    name: "His & Hers Watch Set",
    slug: "his-hers-watch-set",
    description: "A matching pair of luxury automatic watches in a shared presentation box. His: 42mm with steel bracelet. Hers: 36mm with mother-of-pearl dial on leather strap. Swiss movement, sapphire crystal.",
    price: 6800,
    compareAtPrice: 7500,
    images: JSON.stringify(["/images/products/couple-1.jpg"]),
    categorySlug: "couple-gifts",
    stock: 4,
    rating: 4.9,
    reviewCount: 22,
    featured: true,
    tags: JSON.stringify(["watch", "matching", "couple", "swiss"]),
  },
  {
    name: "Couple's Spa Experience Box",
    slug: "couples-spa-experience",
    description: "A luxury at-home spa kit for two. Includes matching bamboo robes, aromatic massage oils, bath bombs, face masks, and a wooden massage tool. Transform any evening into a retreat.",
    price: 420,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/couple-2.jpg"]),
    categorySlug: "couple-gifts",
    stock: 15,
    rating: 4.8,
    reviewCount: 74,
    featured: true,
    tags: JSON.stringify(["spa", "robes", "massage", "relaxation"]),
  },
  {
    name: "Personalized Couple Portrait",
    slug: "personalized-couple-portrait",
    description: "A hand-drawn digital portrait of a couple, created from your photo by a professional artist. Printed on premium canvas and framed in your choice of gold, black, or white frame. A unique keepsake.",
    price: 350,
    compareAtPrice: 450,
    images: JSON.stringify(["/images/products/couple-3.jpg"]),
    categorySlug: "couple-gifts",
    stock: 25,
    rating: 4.6,
    reviewCount: 48,
    featured: false,
    tags: JSON.stringify(["portrait", "custom", "canvas", "framed"]),
  },

  // Men's Shirts & T-Shirts
  {
    name: "Royal White Dress Shirt",
    slug: "royal-white-dress-shirt",
    description: "A pristine white formal dress shirt crafted from the finest two-ply Egyptian cotton. Features a spread collar, French cuffs, and mother-of-pearl buttons. The perfect foundation for black-tie elegance and boardroom authority.",
    price: 480,
    compareAtPrice: 580,
    images: JSON.stringify(["/images/products/mens-shirt-1.jpg"]),
    categorySlug: "mens-shirts",
    stock: 20,
    rating: 4.9,
    reviewCount: 67,
    featured: true,
    tags: JSON.stringify(["dress-shirt", "white", "formal", "egyptian-cotton", "french-cuff"]),
  },
  {
    name: "Navy Oxford Button-Down",
    slug: "navy-oxford-button-down",
    description: "A classic navy Oxford shirt with button-down collar in premium long-staple cotton. The slightly textured Oxford weave gives it character while maintaining a polished look. Perfect for business casual and weekend sophistication.",
    price: 320,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/mens-shirt-2.jpg"]),
    categorySlug: "mens-shirts",
    stock: 25,
    rating: 4.8,
    reviewCount: 89,
    featured: true,
    tags: JSON.stringify(["oxford", "navy", "button-down", "business-casual"]),
  },
  {
    name: "Obsidian Crew Neck Tee",
    slug: "obsidian-crew-neck-tee",
    description: "A luxurious black t-shirt in heavyweight Supima cotton with a rich, substantial feel. The crew neck retains its shape wash after wash, while the slim fit drapes perfectly. The essential foundation of every refined casual wardrobe.",
    price: 145,
    compareAtPrice: 180,
    images: JSON.stringify(["/images/products/mens-shirt-3.jpg"]),
    categorySlug: "mens-shirts",
    stock: 35,
    rating: 4.7,
    reviewCount: 156,
    featured: true,
    tags: JSON.stringify(["t-shirt", "black", "crew-neck", "supima-cotton", "essential"]),
  },
  {
    name: "Mediterranean Linen Shirt",
    slug: "mediterranean-linen-shirt",
    description: "A breezy light blue linen shirt with mandarin collar for effortless summer style. Woven from premium European flax linen that softens beautifully with each wear. The relaxed fit and breathable fabric make it ideal for warm-weather sophistication.",
    price: 380,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/mens-shirt-4.jpg"]),
    categorySlug: "mens-shirts",
    stock: 15,
    rating: 4.8,
    reviewCount: 42,
    featured: true,
    tags: JSON.stringify(["linen", "light-blue", "summer", "mandarin-collar", "relaxed"]),
  },
  {
    name: "Ivory V-Neck Essential Tee",
    slug: "ivory-vneck-essential-tee",
    description: "A premium white V-neck t-shirt in ultra-soft Supima cotton jersey. The clean minimal design features a perfectly proportioned V-neck, reinforced seams, and a slim fit that layers beautifully under blazers or stands alone with style.",
    price: 125,
    compareAtPrice: 160,
    images: JSON.stringify(["/images/products/mens-shirt-5.jpg"]),
    categorySlug: "mens-shirts",
    stock: 40,
    rating: 4.6,
    reviewCount: 203,
    featured: false,
    tags: JSON.stringify(["t-shirt", "white", "v-neck", "supima-cotton", "layering"]),
  },
  {
    name: "Heritage Micro-Check Dress Shirt",
    slug: "heritage-micro-check-dress-shirt",
    description: "A distinguished blue and white micro-check dress shirt with cutaway collar. Crafted from fine two-ply cotton with a subtle textured pattern that adds depth without overwhelming. Pair with a silk tie for the boardroom or wear open-necked for smart casual.",
    price: 420,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/mens-shirt-6.jpg"]),
    categorySlug: "mens-shirts",
    stock: 18,
    rating: 4.8,
    reviewCount: 55,
    featured: true,
    tags: JSON.stringify(["dress-shirt", "check", "cutaway-collar", "two-ply-cotton"]),
  },
  {
    name: "Riviera Striped Polo",
    slug: "riviera-striped-polo",
    description: "A refined navy and white striped polo shirt in premium piqué cotton. The ribbed collar and two-button placket offer classic styling, while the breathable piqué weave keeps you comfortable. European sophistication meets casual elegance.",
    price: 275,
    compareAtPrice: 340,
    images: JSON.stringify(["/images/products/mens-shirt-7.jpg"]),
    categorySlug: "mens-shirts",
    stock: 22,
    rating: 4.7,
    reviewCount: 71,
    featured: true,
    tags: JSON.stringify(["polo", "striped", "piqué", "navy", "casual-luxury"]),
  },
  {
    name: "Cloud Grey Modal-Blend Tee",
    slug: "cloud-grey-modal-blend-tee",
    description: "An impossibly soft heather grey t-shirt in a premium modal-cotton blend. The luxurious drape and silky hand-feel elevate this beyond any ordinary tee. Relaxed fit with a lived-in softness from day one. The ultimate comfort luxury.",
    price: 165,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/mens-shirt-8.jpg"]),
    categorySlug: "mens-shirts",
    stock: 30,
    rating: 4.9,
    reviewCount: 94,
    featured: true,
    tags: JSON.stringify(["t-shirt", "grey", "modal", "soft", "relaxed-fit", "luxury-casual"]),
  },
  {
    name: "Noir Silk Evening Shirt",
    slug: "noir-silk-evening-shirt",
    description: "A dramatic black silk evening shirt with hidden button placket and wing collar. The luxurious silk fabric has a subtle sheen that catches the light, while the clean front creates an uninterrupted line of elegance. For the man who commands the room.",
    price: 890,
    compareAtPrice: null,
    images: JSON.stringify(["/images/products/mens-shirt-9.jpg"]),
    categorySlug: "mens-shirts",
    stock: 8,
    rating: 5.0,
    reviewCount: 23,
    featured: true,
    tags: JSON.stringify(["silk", "black", "evening", "wing-collar", "formal", "hidden-placket"]),
  },
  {
    name: "Sage Henley Long Sleeve",
    slug: "sage-henley-long-sleeve",
    description: "A vintage-inspired dark olive henley in premium slub cotton with a three-button placket and ribbed cuffs. The textured slub yarn gives it a lived-in character, while the relaxed drape channels effortless cool. Pairs perfectly with dark denim or chinos.",
    price: 195,
    compareAtPrice: 240,
    images: JSON.stringify(["/images/products/mens-shirt-10.jpg"]),
    categorySlug: "mens-shirts",
    stock: 20,
    rating: 4.7,
    reviewCount: 63,
    featured: false,
    tags: JSON.stringify(["henley", "olive", "slub-cotton", "long-sleeve", "vintage"]),
  },
];

async function seed() {
  console.log("🌱 Seeding database...");

  // Create categories
  for (const cat of categories) {
    await db.category.upsert({
      where: { slug: cat.slug },
      update: cat,
      create: cat,
    });
  }
  console.log(`✅ Created ${categories.length} categories`);

  // Create products
  let productCounter = 10001;
  for (const prod of products) {
    const category = await db.category.findUnique({
      where: { slug: prod.categorySlug },
    });

    if (!category) {
      console.error(`❌ Category not found: ${prod.categorySlug}`);
      continue;
    }

    const { categorySlug, ...productData } = prod;
    const productNumber = `PRD-${productCounter}`;
    productCounter++;

    await db.product.upsert({
      where: { slug: prod.slug },
      update: { ...productData, categoryId: category.id, productNumber },
      create: { ...productData, categoryId: category.id, productNumber },
    });
  }
  console.log(`✅ Created ${products.length} products`);

  // Create default demo users
  const bcrypt = await import('bcryptjs');
  const demoUsers = [
    {
      email: 'admin@3boxesluxury.com',
      name: 'Admin',
      password: 'admin123',
      role: 'admin' as const,
      permissions: [
        'products.manage', 'orders.manage', 'users.approve', 'users.manage',
        'reports.view', 'settings.manage', 'inventory.manage',
      ],
    },
    {
      email: 'user@3boxesluxury.com',
      name: 'User',
      password: 'user123',
      role: 'user' as const,
      permissions: ['orders.own', 'cart.manage', 'wishlist.manage', 'profile.own'],
    },
    {
      email: 'agent@3boxesluxury.com',
      name: 'Agent',
      password: 'agent123',
      role: 'agent' as const,
      permissions: ['orders.view', 'orders.manage', 'products.view', 'customers.view', 'reports.view'],
    },
    {
      email: 'team@3boxesluxury.com',
      name: 'Team',
      password: 'team123',
      role: 'team' as const,
      permissions: ['orders.view', 'products.view', 'inventory.manage', 'reports.view'],
    },
    {
      email: 'corporate@3boxesluxury.com',
      name: 'TechCorp Industries',
      password: 'corporate123',
      role: 'corporate' as const,
      permissions: ['corporate.manage', 'campaigns.manage', 'branding.manage', 'recipients.manage'],
    },
  ];

  for (const demoUser of demoUsers) {
    const exists = await db.user.findUnique({ where: { email: demoUser.email } });
    if (!exists) {
      const hashedPassword = await bcrypt.hash(demoUser.password, 12);
      await db.user.create({
        data: {
          email: demoUser.email,
          name: demoUser.name,
          password: hashedPassword,
          role: demoUser.role,
          isActive: true,
          approvalStatus: 'approved',
          emailVerified: true,
          phoneVerified: false,
          twoFactorEnabled: false,
          permissions: {
            create: demoUser.permissions.map((p) => ({ permission: p })),
          },
        },
      });
      console.log(`✅ Created demo user: ${demoUser.email} / ${demoUser.password} (${demoUser.role})`);
    } else {
      console.log(`⏭️  Demo user already exists: ${demoUser.email}`);
    }
  }

  // Create corporate account for demo corporate user
  const corpUser = await db.user.findUnique({ where: { email: 'corporate@3boxesluxury.com' } });
  if (corpUser) {
    const existingCorp = await db.corporateAccount.findUnique({ where: { userId: corpUser.id } });
    if (!existingCorp) {
      const corp = await db.corporateAccount.create({
        data: {
          companyName: 'TechCorp Industries',
          slug: 'techcorp-industries',
          industry: 'Technology',
          website: 'https://techcorp.example.com',
          gstNumber: '27AABCT1234F1ZP',
          panNumber: 'AABCT1234F',
          contactName: 'Rajesh Kumar',
          contactEmail: 'rajesh@techcorp.example.com',
          contactPhone: '+91-9876543210',
          address: '123 Tech Park, Cyber City',
          city: 'Gurgaon',
          state: 'Haryana',
          zipCode: '122002',
          userId: corpUser.id,
          approvalStatus: 'approved',
          creditLimit: 500000,
          creditUsed: 0,
          discountPercent: 12,
        },
      });

      await db.corporateBranding.create({
        data: {
          corporateId: corp.id,
          logoUrl: '/images/logo.png',
          primaryColor: '#1e40af',
          secondaryColor: '#f59e0b',
          customMessage: 'Wishing you joy and success this festive season! — TechCorp Industries',
          packagingType: 'premium',
          giftWrapStyle: 'Gold ribbon with branded wrapping',
          includeBranding: true,
          hidePrice: true,
        },
      });

      // Create demo campaigns
      const products = await db.product.findMany({ take: 2 });
      const campaign = await db.corporateCampaign.create({
        data: {
          corporateId: corp.id,
          name: 'Diwali 2026 Corporate Gifts',
          occasion: 'diwali',
          description: 'Annual Diwali gifting for all employees and key clients',
          budgetPerRecipient: 3000,
          totalBudget: 150000,
          status: 'approved',
          deliveryType: 'bulk',
          deliveryDate: new Date('2026-10-20'),
          message: 'May the festival of lights bring you happiness and prosperity!',
          productId: products[0]?.id || null,
        },
      });

      const recipients = [
        { name: 'Priya Sharma', email: 'priya@techcorp.example.com', designation: 'VP Engineering', department: 'Engineering', city: 'Gurgaon', state: 'Haryana' },
        { name: 'Amit Patel', email: 'amit@techcorp.example.com', designation: 'CTO', department: 'Technology', city: 'Bangalore', state: 'Karnataka' },
        { name: 'Sneha Reddy', email: 'sneha@techcorp.example.com', designation: 'Head of Design', department: 'Design', city: 'Mumbai', state: 'Maharashtra' },
        { name: 'Vikram Singh', email: 'vikram@techcorp.example.com', designation: 'Director Sales', department: 'Sales', city: 'Delhi', state: 'Delhi' },
        { name: 'Ananya Gupta', email: 'ananya@techcorp.example.com', designation: 'HR Manager', department: 'Human Resources', city: 'Pune', state: 'Maharashtra' },
      ];
      for (const r of recipients) {
        await db.campaignRecipient.create({ data: { campaignId: campaign.id, ...r } });
      }

      const campaign2 = await db.corporateCampaign.create({
        data: {
          corporateId: corp.id,
          name: 'New Year Team Appreciation',
          occasion: 'new_year',
          description: 'New year appreciation gifts for the leadership team',
          budgetPerRecipient: 5000,
          totalBudget: 50000,
          status: 'pending_approval',
          deliveryType: 'individual',
          deliveryDate: new Date('2027-01-01'),
          message: 'Happy New Year! Thank you for an amazing year ahead.',
          productId: products[1]?.id || null,
        },
      });

      const recipients2 = [
        { name: 'Rajesh Kumar', email: 'rajesh@techcorp.example.com', designation: 'CEO', department: 'Leadership', city: 'Gurgaon', state: 'Haryana' },
        { name: 'Priya Sharma', email: 'priya@techcorp.example.com', designation: 'VP Engineering', department: 'Engineering', city: 'Gurgaon', state: 'Haryana' },
      ];
      for (const r of recipients2) {
        await db.campaignRecipient.create({ data: { campaignId: campaign2.id, ...r } });
      }

      console.log('✅ Created corporate account, branding, and 2 demo campaigns');
    } else {
      console.log('⏭️  Corporate account already exists');
    }
  }
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
