const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

const docs = [
  { title: '3Boxes Technical Architecture', slug: 'technical-architecture', content: '# 3Boxes Technical Architecture\n\n## Overview\n3Boxes Luxury is a full-stack e-commerce platform built on Next.js 16 with App Router, featuring AI-powered virtual try-on, social style integration, and cross-portal shopping.\n\n## Technology Stack\n- Frontend: Next.js 16, React 19, TypeScript 5, Tailwind CSS 4, shadcn/ui\n- Backend: Next.js API Routes, Prisma ORM, SQLite\n- AI/ML: Google Gemini AI for virtual try-on and fashion analysis\n- E-commerce: Shopify Storefront API integration\n- Auth: NextAuth.js v4 with 2FA (OTP via email)\n\n## Key Modules\n1. Product Management - CRUD with Shopify sync\n2. Virtual Try-On - AI-powered clothing visualization\n3. Social Style Integration - FB/LinkedIn/Instagram fashion analysis\n4. 3Box Curate - Cross-portal bundle shopping\n5. Family Shopping - Occasion-based packages\n6. Knowledge Hub - Documentation and training system\n7. Admin Console - Full management dashboard', category: 'architecture', version: '1.0', isPublished: true, accessRoles: 'admin,team,agent,user' },
  { title: 'API Documentation', slug: 'api-documentation', content: '# API Documentation\n\n## Authentication\nAll API endpoints require Bearer token authentication.\n\n## Admin Endpoints\n- GET /api/admin/products - List products\n- POST /api/admin/products - Create product\n- GET /api/admin/orders - List orders\n\n## Wiki / Knowledge Hub\n- GET /api/wiki - List documents (role-based)\n- POST /api/wiki - Create document (admin)\n- GET /api/wiki/[id] - Get document\n- PATCH /api/wiki/[id] - Update document (admin)\n- DELETE /api/wiki/[id] - Delete document (admin)\n\n## Social Style\n- POST /api/social-style - Analyze social profile\n\n## 3Box Curate\n- POST /api/threebox-curate - Bundle shopping\n\n## Family Shopping\n- POST /api/family-shopping - Family packages', category: 'api', version: '1.0', isPublished: true, accessRoles: 'admin,team,agent' },
  { title: 'Standard Operating Procedures', slug: 'standard-operating-procedures', content: '# Standard Operating Procedures\n\n## Admin SOP\n\n### 1. Product Management\n1. Navigate to Products tab in admin dashboard\n2. Click Add Product to create new product\n3. Fill in all required fields (name, price, SKU, category)\n4. Upload product images (minimum 1, recommended 3-5)\n5. Set stock quantity and reorder level\n6. Click Save to publish or save as draft\n\n### 2. Order Processing\n1. Monitor Orders tab for new orders\n2. Verify payment status before processing\n3. Update order status: Pending -> Processing -> Shipped -> Delivered\n4. Add tracking information when shipped\n\n### 3. Inventory Management\n1. Check Inventory tab daily for low stock alerts\n2. Reorder when stock falls below reorder level\n3. Update stock quantities after receiving inventory\n4. Run inventory audit monthly\n\n## Agent SOP\n\n### 1. Document Access\n1. Log in to your agent account\n2. Navigate to Knowledge Hub in the main navigation\n3. Browse available documents by category\n4. Use Download to save documents for offline reference', category: 'sop', version: '1.0', isPublished: true, accessRoles: 'admin,team,agent' },
  { title: 'Training Guide - Admin Dashboard', slug: 'training-admin-dashboard', content: '# Training Guide - Admin Dashboard\n\n## Module 1: Dashboard Overview\nThe dashboard provides a real-time overview of revenue metrics, order statistics, quick stats, recent activity, and quick actions.\n\n## Module 2: Product Management\n1. Click Products then Add Product\n2. Enter product details\n3. Upload images and set categories\n4. Configure inventory\n5. Save as draft or publish\n\n## Module 3: Knowledge Hub\n### Creating Documents\n1. Navigate to Knowledge Hub tab\n2. Click New Document\n3. Fill in Title, Category, Content (Markdown)\n4. Set version number and access roles\n5. Toggle publish/draft status\n6. Save the document\n\n### Document Categories\n- Architecture - System design documents\n- API - API documentation\n- Technical - Technical specifications\n- Training - Training materials\n- Patent - Patent documentation\n- SOP - Standard Operating Procedures\n- General - General documentation', category: 'training', version: '1.0', isPublished: true, accessRoles: 'admin,team' },
  { title: 'Patent Research Documentation', slug: 'patent-research-documentation', content: '# Patent Research Documentation\n\n## Patentable Innovations\n\n### 1. AI Virtual Try-On System\nReal-time AI-powered clothing visualization using user photographs with Gemini AI.\n\n### 2. Cross-Portal Bundle Shopping (3Box Curate)\nAggregation system bundling products from multiple e-commerce portals with unified checkout.\n\n### 3. Social Style Integration\nSystem importing and analyzing social media data for personalized fashion recommendations.\n\n### 4. Family Shopping Occasion Engine\nAI-driven system for family-oriented shopping packages based on occasions and cultural events.\n\n## Filing Status\n- Provisional application planned for Q2 2025\n- Full utility patent application target: Q3 2025\n\n## Confidentiality\nCONFIDENTIAL - Admin and Team roles only.', category: 'patent', version: '1.0', isPublished: true, accessRoles: 'admin,team' },
  { title: 'Functional Documentation', slug: 'functional-documentation', content: '# Functional Documentation\n\n## User Workflows\n\n### Customer Shopping Flow\n1. Browse product catalog\n2. Apply filters (category, price, brand)\n3. View product details with AI virtual try-on\n4. Add items to cart\n5. Proceed to checkout\n6. Complete purchase\n\n### AI Virtual Try-On\n1. Upload photo\n2. Select garment\n3. AI generates try-on visualization\n4. Compare multiple options\n\n### Social Style Integration\n1. Connect social account\n2. Import profile data with consent\n3. AI analyzes fashion preferences\n4. Get personalized recommendations\n\n### 3Box Curate\n1. Activate 3Box Curate\n2. System aggregates partner products\n3. AI curates bundle packages\n4. Unified checkout\n\n### Family Shopping\n1. Select occasion\n2. Get family package recommendations\n3. Customize for family members\n4. One-click purchase', category: 'general', version: '1.0', isPublished: true, accessRoles: 'admin,team,agent,user' },
]

async function main() {
  for (const doc of docs) {
    try {
      await prisma.wikiDocument.upsert({ where: { slug: doc.slug }, update: doc, create: doc })
      console.log('Seeded: ' + doc.title)
    } catch (err) {
      console.error('Failed: ' + doc.title, err.message)
    }
  }
  await prisma.$disconnect()
}
main()
